export type Platform = 'iOS' | 'Android' | 'PC' | 'Switch' | 'PS' | 'Xbox'
export type Style = 'casual' | 'strategy' | 'simulation' | 'rpg' | 'multiplayer'

export interface GameData {
  slug: string
  nameZh: string
  nameEn: string
  descZh: string
  descEn: string
  longDescZh: string
  longDescEn: string
  developerZh: string
  developerEn: string
  year: number
  platforms: Platform[]
  styles: Style[]
  color: string
  emoji: string
  hasTools?: boolean
  hasGuides?: boolean
  featured?: boolean
  features: { zh: string; en: string }[]
  forWhomZh: string
  forWhomEn: string
  tipZh: string
  tipEn: string
  relatedSlugs?: string[]
}

export const PLATFORM_LABELS: Record<Platform, string> = {
  iOS: 'iOS',
  Android: 'Android',
  PC: 'PC / Steam',
  Switch: 'Nintendo Switch',
  PS: 'PlayStation',
  Xbox: 'Xbox',
}

export const STYLE_LABELS_ZH: Record<Style, string> = {
  casual: '休闲',
  strategy: '策略',
  simulation: '模拟经营',
  rpg: 'RPG',
  multiplayer: '多人联机',
}

export const STYLE_LABELS_EN: Record<Style, string> = {
  casual: 'Casual',
  strategy: 'Strategy',
  simulation: 'Simulation',
  rpg: 'RPG',
  multiplayer: 'Multiplayer',
}

export const GAMES: GameData[] = [
  {
    slug: 'hay-day',
    nameZh: 'Hay Day',
    nameEn: 'Hay Day',
    descZh: '超轻松的农场经营游戏，种作物、养动物、做商品、和邻居交易。适合碎片时间。',
    descEn: 'Casual farm management — grow crops, raise animals, craft goods, and trade with neighbors.',
    longDescZh: 'Hay Day 是 Supercell 出品的移动端农场游戏，全球下载量最高的农场类手游之一。游戏核心是种植作物、加工成商品，通过路边摊或船运订单出售。节奏非常轻松，不需要长时间在线，非常适合每天打开几次的玩法。随着等级提升，你可以解锁更多作物、建筑和生产设备，农场规模持续扩大。',
    longDescEn: 'Hay Day is a casual farming game by Supercell — one of the most downloaded farming games on mobile. The core loop is growing crops, processing them into goods, and selling via roadside stands or boat orders. It rewards checking in a few times a day rather than long sessions. As you level up, you unlock more crops, buildings, and production machines.',
    developerZh: 'Supercell',
    developerEn: 'Supercell',
    year: 2012,
    platforms: ['iOS', 'Android'],
    styles: ['casual'],
    color: '#f0a832',
    emoji: '🌻',
    hasTools: true,
    hasGuides: true,
    featured: true,
    features: [
      { zh: '作物种植与加工链——从小麦到面包，步步升级', en: 'Crop-to-product chains — from wheat to bread, step by step' },
      { zh: '路边摊交易，和邻居买卖商品', en: 'Roadside stand trading with neighbors' },
      { zh: '船运和卡车订单，赚取高额金币', en: 'Boat and truck orders for big coin payouts' },
      { zh: '农场动物：鸡、牛、猪、羊，各产不同原料', en: 'Farm animals — chickens, cows, pigs, sheep — each producing unique materials' },
      { zh: '镇子建设，吸引游客增加收入', en: 'Town building to attract visitors and boost income' },
      { zh: '无强制付费，可完全免费游玩', en: 'Free to play — no paywalls blocking core gameplay' },
    ],
    forWhomZh: '适合喜欢轻度农场游戏、每天碎片时间玩几次的休闲玩家。不需要大量时间投入，老少皆宜。',
    forWhomEn: 'Perfect for casual players who want a relaxing farm to check in on throughout the day. No heavy time commitment needed — great for all ages.',
    tipZh: '新手别急着升级仓库和谷仓——先多种小麦和玉米，钱够了再扩建。路边摊定价可以参考邻居的价格，不要卖得太便宜。',
    tipEn: "Don't rush to upgrade your silo and barn early — focus on growing wheat and corn first. When pricing your roadside stand, check neighbor prices instead of defaulting to the minimum.",
    relatedSlugs: ['stardew-valley', 'farmville-3'],
  },
  {
    slug: 'stardew-valley',
    nameZh: '星露谷物语',
    nameEn: 'Stardew Valley',
    descZh: '像素风农场 RPG，经营农场、探索矿洞、与村民交友。内容极其丰富，深度极高。',
    descEn: 'Pixel-art farm RPG — build your farm, explore mines, and befriend townsfolk in a charming world.',
    longDescZh: '星露谷物语是 ConcernedApe（Eric Barone）一人开发的独立游戏，公认的现代农场游戏神作。你继承了祖父在星露谷的农场，在这里种地、采矿、钓鱼、和村民交友，甚至可以结婚生子。游戏内容极其丰富，一周目通常需要 60-100 小时，且有大量模组支持，重玩价值极高。PC 端支持最多 4 人联机。',
    longDescEn: "Stardew Valley is an indie masterpiece by solo developer ConcernedApe (Eric Barone), widely regarded as the best modern farming game. You inherit your grandfather's farm, where you farm, mine, fish, befriend villagers, and can even get married and have children. A first playthrough typically takes 60–100 hours, and robust mod support makes it infinitely replayable. Supports up to 4-player co-op on PC.",
    developerZh: 'ConcernedApe（Eric Barone）',
    developerEn: 'ConcernedApe (Eric Barone)',
    year: 2016,
    platforms: ['PC', 'Switch', 'iOS', 'Android', 'PS', 'Xbox'],
    styles: ['rpg', 'simulation'],
    color: '#7bc67e',
    emoji: '🌱',
    hasTools: true,
    hasGuides: true,
    featured: true,
    features: [
      { zh: '四季轮转，每季有不同作物和活动', en: 'Four distinct seasons with unique crops and events each' },
      { zh: '矿洞探索 + 战斗，解锁稀有材料', en: 'Mine exploration and combat to unlock rare materials' },
      { zh: '12 位可交友/结婚的村民，各有深度剧情', en: '12 friendable/marriageable villagers with rich storylines' },
      { zh: '工匠加工系统，把作物变成高价值商品', en: 'Artisan processing — turn crops into high-value products' },
      { zh: 'PC 最多 4 人联机合作', en: 'Up to 4-player co-op on PC' },
      { zh: '海量模组，社区活跃度极高', en: 'Massive modding community with thousands of mods' },
    ],
    forWhomZh: '适合想要深度内容的玩家。如果你喜欢慢慢建设、探索剧情、享受长线成长，星露谷是最好的选择之一。性价比极高。',
    forWhomEn: 'Ideal for players who want depth and long-term progression. If you enjoy slow-building, story exploration, and seeing your efforts pay off over time, Stardew Valley is among the best options available.',
    tipZh: '春季第一年优先种防风草和土豆，资金充裕后升级背包。每天记得去村民家门口送礼，好感度慢慢积累很重要。',
    tipEn: "Plant parsnips and potatoes in Spring Year 1 to build up funds quickly. Gift villagers daily — relationship-building unlocks major story content.",
    relatedSlugs: ['hay-day', 'coral-island'],
  },
  {
    slug: 'animal-crossing',
    nameZh: '动物森友会',
    nameEn: 'Animal Crossing: New Horizons',
    descZh: '在无人岛上建立自己的小天地，和动物邻居相处，每天都有新发现。',
    descEn: 'Build your dream island, befriend animal villagers, and enjoy the slow pace of island life.',
    longDescZh: '动物森友会：新视野（ACNH）是任天堂出品的生活模拟游戏，玩家在一座无人岛上从零开始建设。游戏和现实时间同步，每天都有不同的事件、昆虫鱼类和季节变化。岛屿可以自由地形改造，设计感极强，非常适合喜欢"装扮和展示"的玩家。',
    longDescEn: 'Animal Crossing: New Horizons (ACNH) is a life simulation by Nintendo where you build your own island paradise from scratch. The game runs on real-world time, with daily events, seasonal fish and bugs, and changing weather. You can terraform the entire island layout, making it a favorite for creative players who love designing and showing off their spaces.',
    developerZh: '任天堂',
    developerEn: 'Nintendo',
    year: 2020,
    platforms: ['Switch'],
    styles: ['casual', 'simulation'],
    color: '#5db8b2',
    emoji: '🏝️',
    hasGuides: true,
    featured: true,
    features: [
      { zh: '无人岛从零建设，自由度极高', en: 'Build your island from scratch with total creative freedom' },
      { zh: '地形改造工具，完全重塑岛屿面貌', en: 'Terraforming tools to completely reshape your island' },
      { zh: '约 400 种动物邻居，可邀请最爱的来住', en: '~400 animal villagers — invite your favorites to move in' },
      { zh: '和现实时间同步，每天有不同活动', en: 'Synced to real time — different activities every day' },
      { zh: '线上访问朋友岛屿，交换物品', en: "Visit friends' islands online and trade items" },
      { zh: '四季活动：万圣节、圣诞、新年……', en: "Seasonal events: Halloween, Christmas, New Year's, and more" },
    ],
    forWhomZh: '适合喜欢慢节奏生活模拟、创意设计和社交分享的玩家。如果你喜欢"把家装扮得好看然后给朋友看"，这是你的游戏。',
    forWhomEn: 'Perfect for players who enjoy slow-paced life sims, creative island design, and social sharing. If you love decorating spaces and showing them off to friends, this is your game.',
    tipZh: '每天坚持登录哪怕 10 分钟——和邻居说话、摘化石、钓鱼，好感度和进度都靠每天积累。',
    tipEn: "Log in for even 10 minutes daily — talk to villagers, dig fossils, and fish. Progression in ACNH is built on daily habits.",
    relatedSlugs: ['stardew-valley', 'littlewood'],
  },
  {
    slug: 'farming-simulator',
    nameZh: 'Farming Simulator 25',
    nameEn: 'Farming Simulator 25',
    descZh: '高度写实的农业模拟，驾驶真实农机、管理农场、支持多人合作。硬核向。',
    descEn: 'Realistic agricultural simulation with real machinery brands, crop management, and multiplayer.',
    longDescZh: 'Farming Simulator 是农业模拟游戏系列的标杆，由瑞士 Giants Software 开发。游戏使用真实品牌农机（John Deere、Fendt、Case IH 等），涵盖播种、施肥、除草、收割等完整农业流程。支持最多 16 人在线联机。模组社区极其活跃，有数万个模组可下载。',
    longDescEn: 'Farming Simulator is the benchmark agricultural simulation series, developed by Giants Software. It features real licensed machinery brands (John Deere, Fendt, Case IH) across a complete farming workflow: plowing, sowing, fertilizing, weeding, and harvesting. Supports up to 16-player online co-op. Tens of thousands of community mods dramatically extend replayability.',
    developerZh: 'Giants Software',
    developerEn: 'Giants Software',
    year: 2024,
    platforms: ['PC', 'PS', 'Xbox'],
    styles: ['simulation', 'multiplayer'],
    color: '#8a9a7a',
    emoji: '🚜',
    featured: true,
    features: [
      { zh: '授权真实农机品牌：John Deere、Fendt、Case IH 等', en: 'Licensed real machinery: John Deere, Fendt, Case IH, and more' },
      { zh: '完整农业流程：耕地、播种、施肥、收割', en: 'Full farming workflow: plowing, sowing, fertilizing, harvesting' },
      { zh: '最多 16 人在线联机', en: 'Up to 16-player online co-op' },
      { zh: '畜牧业：牛、猪、羊、鸡', en: 'Animal husbandry: cows, pigs, sheep, and chickens' },
      { zh: '数万个社区模组，内容无限扩展', en: 'Tens of thousands of community mods for endless content' },
      { zh: '多张地图，包含欧洲和北美农业风貌', en: 'Multiple maps featuring European and North American landscapes' },
    ],
    forWhomZh: '适合对农业机械有兴趣、喜欢管理复杂系统的硬核玩家。如果你小时候喜欢拖拉机，这个游戏会让你着迷。',
    forWhomEn: 'Ideal for players interested in real agriculture and managing complex systems. If you ever dreamed of driving a tractor, this game will captivate you.',
    tipZh: '新手从小麦和大麦开始——流程简单，设备便宜。不要一开始就借贷买大型设备，慢慢积累资金再升级。',
    tipEn: 'Start with wheat and barley — simple workflow, affordable equipment. Avoid large loans early; build up funds gradually before upgrading to bigger machinery.',
    relatedSlugs: ['ranch-simulator'],
  },
  {
    slug: 'coral-island',
    nameZh: 'Coral Island',
    nameEn: 'Coral Island',
    descZh: '热带海岛农场生活，融合环保主题，可以下潜清洁珊瑚礁。星露谷风格的进化版。',
    descEn: 'Tropical island farming with an eco-friendly twist — dive to clean coral reefs and befriend islanders.',
    longDescZh: 'Coral Island 是一款以热带海岛为背景的农场 RPG，由马来西亚独立工作室 Stairway Games 开发。除了经典农场经营外，游戏加入了独特的海洋生态玩法：你可以潜入海底清洁珊瑚礁，恢复海洋生态，这会直接影响岛屿资源和村民生活。游戏有 70+ 位可交友的村民，多元文化背景，充满东南亚热带风情。',
    longDescEn: 'Coral Island is a tropical farming RPG by Malaysian indie studio Stairway Games. Beyond classic farm management, it adds a unique ocean ecology system: diving underwater to clean coral reefs and restore the marine ecosystem, which directly affects island resources and villager life. Features 70+ friendable villagers with diverse cultural backgrounds and a vibrant Southeast Asian tropical aesthetic.',
    developerZh: 'Stairway Games',
    developerEn: 'Stairway Games',
    year: 2023,
    platforms: ['PC', 'Switch', 'PS', 'Xbox'],
    styles: ['rpg', 'simulation'],
    color: '#4db8d4',
    emoji: '🪸',
    features: [
      { zh: '海底潜水玩法——清洁珊瑚礁，恢复生态', en: 'Underwater diving — clean coral reefs and restore the ecosystem' },
      { zh: '70+ 位多元文化背景的村民', en: '70+ villagers with diverse cultural backgrounds' },
      { zh: '热带农业：种植热带作物和香料', en: 'Tropical farming with exotic crops and spices' },
      { zh: '环保主题贯穿游戏进度', en: 'Environmental conservation woven into the main progression' },
      { zh: '精美的热带视觉风格', en: 'Beautiful tropical art style and island atmosphere' },
    ],
    forWhomZh: '适合星露谷爱好者寻求新鲜感的玩家，以及喜欢热带风情和环保主题的玩家。',
    forWhomEn: 'Great for Stardew Valley fans looking for something fresh, and players drawn to tropical aesthetics and environmental themes.',
    tipZh: '不要忽视海底清洁任务——珊瑚礁健康度会直接影响你能捕到的鱼类和获得的材料。',
    tipEn: "Don't neglect underwater cleaning missions — coral reef health directly affects what fish and materials you can find.",
    relatedSlugs: ['stardew-valley', 'roots-of-pacha'],
  },
  {
    slug: 'roots-of-pacha',
    nameZh: 'Roots of Pacha',
    nameEn: 'Roots of Pacha',
    descZh: '石器时代农场游戏，帮助史前部落发现农业、驯化动物、发明工具。独特的历史背景。',
    descEn: 'Stone Age farming — help your prehistoric tribe discover agriculture, tame animals, and invent tools.',
    longDescZh: 'Roots of Pacha 把农场游戏的舞台设在了史前时代。你不是在经营一个已有的农场，而是帮助整个部落"发明"农业——驯化野生动物、培育野生植物成为可种植的作物、开发各种工具和技术。每一个发现都是真正的里程碑，有着历史感的满足感。支持 4 人联机。',
    longDescEn: "Roots of Pacha sets farming in the prehistoric era. Instead of managing an existing farm, you help an entire tribe \"invent\" agriculture — taming wild animals, cultivating wild plants into farmable crops, and developing tools and technologies. Every discovery feels like a genuine milestone. Supports 4-player co-op.",
    developerZh: 'Soda Den',
    developerEn: 'Soda Den',
    year: 2023,
    platforms: ['PC', 'Switch', 'PS', 'Xbox'],
    styles: ['rpg', 'simulation'],
    color: '#c4834a',
    emoji: '🪨',
    features: [
      { zh: '史前世界设定，历史感十足', en: 'Prehistoric setting with authentic historical feel' },
      { zh: '帮助部落从采集进化到农耕文明', en: 'Guide your tribe from hunter-gatherer to agricultural civilization' },
      { zh: '驯化野生动物，培育野生作物', en: 'Tame wild animals and cultivate wild plants' },
      { zh: '4 人在线联机', en: '4-player online co-op' },
      { zh: '独特的"发现"进度系统', en: 'Unique "discovery" progression system' },
    ],
    forWhomZh: '适合想要体验不同于普通农场游戏背景的玩家，以及对人类文明早期农业发展有兴趣的人。',
    forWhomEn: 'Perfect for players who want a farming game with a genuinely different premise, especially those interested in the origins of human civilization and agriculture.',
    tipZh: '多花时间探索地图的每个角落，很多驯化机会和发现线索是在野外偶然遇到的。',
    tipEn: 'Explore every corner of the map — many taming opportunities and discovery triggers are found by wandering rather than waiting.',
    relatedSlugs: ['stardew-valley', 'coral-island'],
  },
  {
    slug: 'ranch-simulator',
    nameZh: 'Ranch Simulator',
    nameEn: 'Ranch Simulator',
    descZh: '第一人称农场牧场模拟，从废弃的祖父农场重新开始，管理牲畜、种植作物、建设建筑。',
    descEn: "First-person ranch simulation — rebuild your grandfather's abandoned farm, raise livestock, and grow crops.",
    longDescZh: 'Ranch Simulator 是一款第一人称视角的农场和牧场模拟游戏。你继承了祖父废弃的农场，从废墟开始重建——修缮建筑、购买牲畜、种植作物，逐步将荒废的农场恢复生机。游戏真实感很强，有砍柴、挖井、建造等手工劳作内容。支持 4 人联机合作。',
    longDescEn: "Ranch Simulator is a first-person farm and ranch simulation. You inherit your grandfather's abandoned farm and rebuild from ruins — repairing buildings, buying livestock, growing crops, and gradually restoring the neglected land. Highly realistic with manual labor like chopping wood, digging wells, and construction. Supports 4-player co-op.",
    developerZh: 'Excalibur Games',
    developerEn: 'Excalibur Games',
    year: 2021,
    platforms: ['PC'],
    styles: ['simulation', 'multiplayer'],
    color: '#8B5E3C',
    emoji: '🏚️',
    features: [
      { zh: '第一人称视角，沉浸感强', en: 'First-person perspective for deep immersion' },
      { zh: '从废墟重建农场，成就感满满', en: 'Rebuild from ruins — highly satisfying progression' },
      { zh: '养殖牛、猪、鸡、羊等各种牲畜', en: 'Raise cows, pigs, chickens, sheep, and more' },
      { zh: '手工建造系统，可搭建各种建筑', en: 'Manual construction system for building structures' },
      { zh: '4 人在线联机', en: '4-player online co-op' },
    ],
    forWhomZh: '适合喜欢 3D 沉浸式农场体验、想要动手建造和改造的玩家，尤其推荐喜欢多人合作的朋友。',
    forWhomEn: 'Great for players who want an immersive 3D farming experience with hands-on construction and co-op play.',
    tipZh: '优先修缮鸡舍，鸡是最便宜的牲畜且收益稳定。卖鸡蛋积累启动资金再扩大规模。',
    tipEn: "Repair the chicken coop first — chickens are the cheapest livestock with reliable returns. Sell eggs to build startup capital before scaling up.",
    relatedSlugs: ['farming-simulator'],
  },
  {
    slug: 'littlewood',
    nameZh: 'Littlewood',
    nameEn: 'Littlewood',
    descZh: '击败大魔王之后的故事——作为失忆的英雄，带领村民重建小镇。超轻松无压力。',
    descEn: 'Post-hero life sim — rebuild your town after the Dark Wizard is defeated, with no combat, no pressure.',
    longDescZh: 'Littlewood 是一款独树一帜的农场+城镇建设游戏。故事发生在"打败大魔王之后"——你是那个英雄，但失去了记忆。现在的任务不是冒险，而是帮助受伤的世界重建小镇、恢复正常生活。游戏没有战斗系统，完全聚焦在建设、收集和村民互动上，节奏极其轻松。',
    longDescEn: "Littlewood is a uniquely positioned farming and town-building game. The story takes place after the Dark Wizard has been defeated — you're the hero who did it, but you've lost your memory. There's no combat; the focus is entirely on rebuilding the town, collecting resources, and befriending villagers. Exceptionally relaxed pace.",
    developerZh: 'Sean Young Games',
    developerEn: 'Sean Young Games',
    year: 2021,
    platforms: ['PC', 'Switch'],
    styles: ['casual', 'simulation'],
    color: '#e8b84b',
    emoji: '🏘️',
    features: [
      { zh: '无战斗系统，纯粹的建设与收集', en: 'No combat — pure building and collecting' },
      { zh: '后英雄时代的独特剧情背景', en: 'Unique post-hero story premise' },
      { zh: '自由定制小镇布局', en: 'Freely customize your town layout' },
      { zh: '多位村民，可交友和解锁技能', en: 'Multiple villagers to befriend and unlock skills from' },
      { zh: '超轻松氛围，无压力游玩', en: 'Exceptionally cozy and low-pressure atmosphere' },
    ],
    forWhomZh: '适合不喜欢战斗系统、只想纯粹享受建设和社交的玩家。极度适合解压。',
    forWhomEn: 'Perfect for players who dislike combat and just want to enjoy building and socializing. One of the most genuinely stress-free farming games available.',
    tipZh: '多和村民交谈解锁技能，游戏里的技能树非常重要，直接影响资源收集效率。',
    tipEn: "Talk to villagers regularly to unlock skills — the skill tree significantly affects resource collection efficiency throughout the game.",
    relatedSlugs: ['animal-crossing', 'stardew-valley'],
  },
  {
    slug: 'my-time-at-portia',
    nameZh: '波西亚时光',
    nameEn: 'My Time at Portia',
    descZh: '末世后的小镇重建游戏，收集古代文明残骸，制造物品，和镇民交友。RPG + 农场的完美融合。',
    descEn: 'Post-apocalyptic town sim — gather ruins of ancient civilizations, craft items, and befriend townsfolk.',
    longDescZh: '波西亚时光是一款后末世世界观的农场+工坊 RPG。你来到波西亚镇，继承父亲的工坊，通过挖掘废弃遗迹获取古代文明部件，将其制造成各种有用的物品。游戏有丰富的镇民关系系统、结婚机制、战斗内容和大量任务线。制造系统非常深度，是游戏核心玩法。',
    longDescEn: "My Time at Portia is a post-apocalyptic farming and crafting RPG. You inherit your father's workshop in Portia town, mining abandoned ruins for ancient civilization parts and crafting them into useful items. Features a rich villager relationship system, marriage mechanics, combat, and extensive quest lines. Deep crafting system is the core gameplay.",
    developerZh: 'Pathea Games',
    developerEn: 'Pathea Games',
    year: 2019,
    platforms: ['PC', 'Switch', 'PS', 'Xbox', 'iOS', 'Android'],
    styles: ['rpg', 'simulation'],
    color: '#f4c06f',
    emoji: '⚙️',
    features: [
      { zh: '深度工坊制造系统，收集古代零件', en: 'Deep crafting system with ancient civilization parts' },
      { zh: '后末世世界观，探索废弃遗迹', en: 'Post-apocalyptic world with ruins to explore' },
      { zh: '丰富的镇民关系和结婚系统', en: 'Rich villager relationships and marriage system' },
      { zh: '战斗内容 + 地下城探索', en: 'Combat system and dungeon exploration' },
      { zh: '大量任务线和主线剧情', en: 'Extensive side quests and main storyline' },
    ],
    forWhomZh: '适合喜欢有丰富制造系统和剧情内容的 RPG 玩家。如果你觉得星露谷缺少制造深度，可以试试这款。',
    forWhomEn: "Great for RPG fans who want deeper crafting and story content. If you feel Stardew Valley lacks crafting depth, this is a strong alternative.",
    tipZh: '优先完成镇委会任务单，能解锁很多后续内容。别忘了每天和镇民打招呼，社交关系提升很慢但很重要。',
    tipEn: 'Prioritize Commerce Guild commission tasks early — they unlock significant content. Greet townsfolk daily; social relationships build slowly but matter a lot.',
    relatedSlugs: ['stardew-valley', 'my-time-at-sandrock'],
  },
  {
    slug: 'my-time-at-sandrock',
    nameZh: '沙石镇时光',
    nameEn: 'My Time at Sandrock',
    descZh: '波西亚时光的精神续作，荒漠小镇背景，制造、建设、拯救沙漠中的小镇。更多内容更大世界。',
    descEn: 'Spiritual sequel to Portia — a desert town to rebuild with deeper crafting and a bigger world.',
    longDescZh: '沙石镇时光是波西亚时光的精神续作，将舞台移至干旱荒漠中的小镇 Sandrock。玩法核心类似——收集材料、制造物品、接受任务、建立关系——但规模更大、系统更深、画面更精美。有大量可探索的沙漠遗迹和更加丰富的剧情内容。支持多人联机。',
    longDescEn: 'My Time at Sandrock is the spiritual sequel to Portia, set in the arid desert town of Sandrock. Core gameplay is similar — gather materials, craft items, take commissions, build relationships — but at a larger scale with deeper systems and better visuals. Features extensive desert ruins to explore and richer story content. Supports multiplayer.',
    developerZh: 'Pathea Games',
    developerEn: 'Pathea Games',
    year: 2023,
    platforms: ['PC', 'Switch', 'PS', 'Xbox'],
    styles: ['rpg', 'simulation', 'multiplayer'],
    color: '#d4874a',
    emoji: '🏜️',
    features: [
      { zh: '荒漠小镇背景，独特的西部风情', en: 'Desert town setting with unique frontier atmosphere' },
      { zh: '比波西亚时光更大的世界和更深的系统', en: 'Larger world and deeper systems than Portia' },
      { zh: '多人联机合作', en: 'Multiplayer co-op support' },
      { zh: '丰富的沙漠遗迹探索', en: 'Extensive desert ruins exploration' },
      { zh: '深度制造和建设系统', en: 'Deep crafting and construction systems' },
    ],
    forWhomZh: '适合玩过波西亚时光并想要更多内容的玩家，或者喜欢沙漠西部风格 RPG 的玩家。',
    forWhomEn: 'Perfect for fans of Portia who want more content, or RPG players drawn to desert frontier settings.',
    tipZh: '水是沙漠里的关键资源，早期优先建水渠，充足的水供给会让后期制造轻松很多。',
    tipEn: 'Water is critical in the desert — prioritize building water infrastructure early. Adequate water supply makes mid-game crafting much easier.',
    relatedSlugs: ['my-time-at-portia', 'stardew-valley'],
  },
  {
    slug: 'sun-haven',
    nameZh: 'Sun Haven',
    nameEn: 'Sun Haven',
    descZh: '有魔法和龙的农场 RPG，在人类村庄、精灵森林和龙城三个世界间切换。战斗内容丰富。',
    descEn: 'Farming RPG with magic and dragons — switch between a human village, elven forest, and dragon city.',
    longDescZh: 'Sun Haven 是一款融合了奇幻元素的农场 RPG。游戏有三个不同的世界可以居住和耕种：人类的 Sun Haven 村庄、精灵的 Nel\'Vari 森林、以及龙族的 Withergate 城市。每个世界都有独特的作物、居民和任务线。战斗系统比星露谷更加丰富，有多种职业可以选择。支持最多 8 人联机。',
    longDescEn: "Sun Haven is a fantasy farming RPG with three distinct worlds: the human Sun Haven village, the elven Nel'Vari forest, and the dragon Withergate city. Each world has unique crops, residents, and quest lines. Combat is more developed than Stardew Valley, with multiple playable classes. Supports up to 8-player multiplayer.",
    developerZh: 'Pixel Sprout Studios',
    developerEn: 'Pixel Sprout Studios',
    year: 2023,
    platforms: ['PC', 'Switch'],
    styles: ['rpg', 'simulation', 'multiplayer'],
    color: '#f5a623',
    emoji: '🐉',
    features: [
      { zh: '三个独立世界：人类村庄、精灵森林、龙族城市', en: 'Three distinct worlds: human village, elven forest, dragon city' },
      { zh: '多职业战斗系统，比星露谷更丰富', en: 'Multi-class combat system, more developed than Stardew Valley' },
      { zh: '最多 8 人联机', en: 'Up to 8-player multiplayer' },
      { zh: '每个世界有独特作物和居民', en: 'Unique crops and residents in each world' },
      { zh: '丰富的奇幻剧情和任务', en: 'Rich fantasy storyline and quests' },
    ],
    forWhomZh: '适合喜欢奇幻元素、想要更多战斗内容和大型多人联机体验的农场游戏玩家。',
    forWhomEn: 'Great for farming game fans who want more fantasy elements, richer combat, and large-scale multiplayer.',
    tipZh: '三个世界都要定期切换——有些作物和任务只在特定世界里完成，忽视某个世界会阻碍进度。',
    tipEn: "Switch between all three worlds regularly — some crops and quests are world-specific, and neglecting one world will block overall progression.",
    relatedSlugs: ['stardew-valley', 'coral-island'],
  },
  {
    slug: 'farmville-3',
    nameZh: 'FarmVille 3',
    nameEn: 'FarmVille 3',
    descZh: '农场游戏经典系列的现代版，专为手机端优化。轻度建设，多种动物，适合极度休闲玩家。',
    descEn: 'Modern take on the classic Facebook game — mobile-optimized, light building, lots of animals.',
    longDescZh: 'FarmVille 3 是 Zynga 出品的经典农场手游系列的最新作。相比初代的 Facebook 时代，这款游戏画面精美，移动端体验优化良好，但仍保持了 FarmVille 系列的轻度休闲基调。种植作物、饲养动物、完成任务，内容简单直接，适合想要纯粹放松的玩家。',
    longDescEn: "FarmVille 3 is the latest entry in Zynga's classic farming series, updated for modern mobile with polished graphics and a better mobile UX. It retains the light, casual FarmVille formula: plant crops, raise animals, complete quests. Simple and direct — ideal for pure relaxation.",
    developerZh: 'Zynga',
    developerEn: 'Zynga',
    year: 2021,
    platforms: ['iOS', 'Android'],
    styles: ['casual'],
    color: '#6abf5e',
    emoji: '🐄',
    features: [
      { zh: '精美的 3D 画面，移动端体验优良', en: 'Polished 3D visuals optimized for mobile' },
      { zh: '多种可爱动物可饲养', en: 'Wide variety of cute animals to raise' },
      { zh: '轻松的任务系统', en: 'Easygoing quest system' },
      { zh: '社交功能，可访问朋友农场', en: "Social features to visit friends' farms" },
      { zh: '零门槛，完全适合新手', en: 'Zero barrier to entry, perfect for beginners' },
    ],
    forWhomZh: '适合只想随手玩几分钟、对深度玩法没有需求的极度休闲玩家。经典 FarmVille 粉丝的最佳选择。',
    forWhomEn: 'Ideal for players who just want to tap around for a few minutes without any depth requirement. Best choice for classic FarmVille fans.',
    tipZh: '优先完成每日任务，奖励是资源获取最高效的途径。不要在仓库装满之前去收集作物。',
    tipEn: "Always complete daily quests first — they're the most efficient source of resources. Don't harvest crops until you have storage space ready.",
    relatedSlugs: ['hay-day'],
  },
  {
    slug: 'garden-paws',
    nameZh: 'Garden Paws',
    nameEn: 'Garden Paws',
    descZh: '在祖父的小岛上建设商店和花园，和可爱的动物居民一起生活。极度治愈的休闲游戏。',
    descEn: "Build shops and gardens on your grandpa's island with cute animal residents — cozy and charming.",
    longDescZh: 'Garden Paws 是一款超治愈的农场+小镇建设游戏。你继承了祖父在小岛上的小镇，养动物、种花园、建商店、迎接各种可爱的动物居民。游戏没有任何压力机制，纯粹享受建设和收集的乐趣。支持 2 人本地或在线联机。',
    longDescEn: "Garden Paws is an extremely cozy farming and town-building game. You inherit your grandfather's island town, raise animals, tend gardens, build shops, and welcome adorable animal residents. No pressure mechanics whatsoever — pure building and collecting joy. Supports 2-player local or online co-op.",
    developerZh: 'Bitten Toast Games',
    developerEn: 'Bitten Toast Games',
    year: 2019,
    platforms: ['PC', 'Switch'],
    styles: ['casual', 'simulation'],
    color: '#9cc96b',
    emoji: '🐾',
    features: [
      { zh: '可爱的动物角色和居民', en: 'Adorable animal characters and residents' },
      { zh: '建设商店，经营小生意', en: 'Build and run your own shops' },
      { zh: '丰富的花园和装饰系统', en: 'Rich gardening and decoration system' },
      { zh: '2 人联机，可以和朋友一起玩', en: '2-player co-op, local or online' },
      { zh: '零压力，随时保存，随时退出', en: 'Zero pressure — save and quit anytime' },
    ],
    forWhomZh: '适合喜欢极度轻松治愈氛围的玩家，非常适合带着小朋友一起玩，或者单纯想放空的时候。',
    forWhomEn: 'Perfect for players who want maximum coziness with zero stress. Great for playing with kids or unwinding after a long day.',
    tipZh: '先把镇子的基础设施建好再去养更多动物，仓库空间是早期最大的瓶颈。',
    tipEn: 'Build up town infrastructure before adding more animals — storage space is the biggest early bottleneck.',
    relatedSlugs: ['animal-crossing', 'littlewood'],
  },
  {
    slug: 'potion-permit',
    nameZh: 'Potion Permit',
    nameEn: 'Potion Permit',
    descZh: '作为炼药师来到新小镇，采集材料、配制药水、为村民治病。医疗主题的独特农场 RPG。',
    descEn: 'Play as a chemist in a new town — gather ingredients, brew potions, and heal sick villagers.',
    longDescZh: 'Potion Permit 是一款以炼药和医疗为核心的农场 RPG。你作为一名化学师来到 Moonbury 小镇，通过采集、战斗获得原材料，配制各种药水为生病的村民治病。游戏的诊断和配药系统很有创意，采用类似心率图的迷你游戏来诊断病情。有完整的社交和解锁剧情内容。',
    longDescEn: 'Potion Permit is a farming RPG centered on alchemy and medicine. As a chemist arriving in Moonbury town, you gather ingredients through exploration and combat, brew potions, and heal sick villagers. Features a creative diagnosis system using rhythm-game-style minigames. Complete social system with unlockable storylines.',
    developerZh: 'MassHive Media',
    developerEn: 'MassHive Media',
    year: 2022,
    platforms: ['PC', 'Switch', 'PS', 'Xbox', 'iOS', 'Android'],
    styles: ['rpg', 'casual'],
    color: '#9b59b6',
    emoji: '⚗️',
    features: [
      { zh: '独特的炼药和医疗核心玩法', en: 'Unique alchemy and medicine core gameplay' },
      { zh: '创意诊断系统（心率图迷你游戏）', en: 'Creative diagnosis minigame system' },
      { zh: '采集 + 战斗获取材料', en: 'Gather ingredients through exploration and combat' },
      { zh: '村民故事线和社交系统', en: 'Villager storylines and social system' },
      { zh: '移动端表现出色', en: 'Excellent mobile performance' },
    ],
    forWhomZh: '适合喜欢独特主题和创意玩法的玩家。如果你觉得普通农场游戏太雷同，炼药师视角会带来新鲜感。',
    forWhomEn: 'Great for players who want something thematically unique. If standard farming games feel too familiar, the alchemist-healer angle offers genuine freshness.',
    tipZh: '每天先去诊所看看有没有新病人，再出门采集材料。诊疗进度直接影响村民好感度解锁速度。',
    tipEn: 'Check the clinic for new patients before heading out to gather. Healing progress directly affects how quickly villager relationships unlock.',
    relatedSlugs: ['stardew-valley', 'coral-island'],
  },
  {
    slug: 'spirittea',
    nameZh: 'Spirittea',
    nameEn: 'Spirittea',
    descZh: '经营精灵泡澡堂，帮助日本风格神灵解决烦恼。结合民俗文化的独特农场 RPG。',
    descEn: 'Run a spirit bathhouse, solve ghost problems in a Japanese folklore-inspired farming RPG.',
    longDescZh: 'Spirittea 是一款以日本民俗文化为灵感的农场+泡澡堂经营游戏。你喝下一杯神秘的茶，获得了看见神灵的能力，并被委托经营一家让神灵们放松的泡澡堂。游戏有 50+ 位神灵角色，每位都有独特的故事和需求，结合了农场采集、社交解谜和澡堂经营三种玩法。',
    longDescEn: "Spirittea is a farming and bathhouse management game inspired by Japanese folklore. After drinking a mysterious tea that lets you see spirits, you're tasked with running a bathhouse where spirits can relax. Features 50+ spirit characters with unique stories. Combines farming, social puzzle-solving, and management.",
    developerZh: 'Cheesemaster Games',
    developerEn: 'Cheesemaster Games',
    year: 2023,
    platforms: ['PC', 'Switch'],
    styles: ['casual', 'simulation'],
    color: '#4a90d9',
    emoji: '♨️',
    features: [
      { zh: '独特的泡澡堂经营核心玩法', en: 'Unique bathhouse management core gameplay' },
      { zh: '50+ 位神灵角色，各有故事', en: '50+ spirit characters with unique stories' },
      { zh: '日本民俗文化风格，视觉独特', en: 'Japanese folklore aesthetic — visually distinct' },
      { zh: '社交解谜元素，帮神灵解决烦恼', en: 'Social puzzle elements — help spirits resolve their issues' },
      { zh: '农场采集作为核心资源循环', en: 'Farming and foraging as core resource loop' },
    ],
    forWhomZh: '适合喜欢日本文化、神灵主题和独特经营玩法的玩家。非常适合喜欢《千与千寻》的人。',
    forWhomEn: "Perfect for fans of Japanese culture, spirit themes, and unique management gameplay. Highly recommended for fans of Spirited Away.",
    tipZh: '先摸清楚每位神灵的活动规律，然后在固定时间去他们出现的地点交互解决问题，效率高很多。',
    tipEn: "Learn each spirit's schedule first, then interact with them at their regular locations — far more efficient than random exploration.",
    relatedSlugs: ['animal-crossing', 'stardew-valley'],
  },
]

export function getGameBySlug(slug: string): GameData | undefined {
  return GAMES.find((g) => g.slug === slug)
}

export function getAllGameSlugs(): string[] {
  return GAMES.map((g) => g.slug)
}

export function getFeaturedGames(): GameData[] {
  return GAMES.filter((g) => g.featured)
}
