// AUTO-GENERATED from the official per-language Stardew Valley wiki Cooking page
// (en/de/ja/ko/zh/zh-hant) via <scratchpad>/gen_cooking.py, sourced from
// <scratchpad>/cooking_raw.json. Do not edit by hand — regenerate from source.

export type CookLoc = { en: string; zh: string; zhTW: string; ja: string; ko: string; de: string }
export type BuffType =
  | 'farming' | 'fishing' | 'foraging' | 'mining' | 'combat' | 'luck'
  | 'attack' | 'defense' | 'speed' | 'maxEnergy' | 'magnetism'
export type SourceCat = 'skill' | 'friendship' | 'shop' | 'tv' | 'other'
export interface CookIngredient { key: string; name: CookLoc; qty: number }
export interface CookBuff { type: BuffType; amount: number }
export interface CookRecipe {
  key: string
  icon: string
  name: CookLoc
  ingredients: CookIngredient[]
  source: CookLoc            // full localized unlock text
  sourceCat: SourceCat       // bucket for filtering
  energy: number
  health: number
  buffs: CookBuff[]          // [] when none
  buffDuration: string | null
  sellPrice: number
}

export const COOK_RECIPES: CookRecipe[] = [
  { key: "algae-soup", icon: "Algae_Soup.png", name: { en: "Algae Soup", zh: "海藻汤", zhTW: "海藻湯", ja: "藻のスープ", ko: "녹조류 스프", de: "Algensuppe" }, ingredients: [{ key: "green-algae", name: { en: "Green Algae", zh: "绿藻", zhTW: "綠藻", ja: "緑の藻", ko: "녹조류", de: "Grünalge" }, qty: 4 }], source: { en: "Clint (Mail - 3+)", zh: "克林特（邮件- 3+）", zhTW: "克林特（郵件- 3+）", ja: "クリント（手紙 - 3+）", ko: "클린트 (우편 - 3 이상)", de: "Clint (per Brief - 3+)" }, sourceCat: "friendship", energy: 75, health: 33, buffs: [], buffDuration: null, sellPrice: 100 },
  { key: "artichoke-dip", icon: "Artichoke_Dip.png", name: { en: "Artichoke Dip", zh: "水煮洋蓟", zhTW: "水煮洋薊", ja: "アーティチョークディップ", ko: "아티초크 소스", de: "Artischockendip" }, ingredients: [{ key: "artichoke", name: { en: "Artichoke", zh: "洋蓟", zhTW: "洋薊", ja: "アーティチョーク", ko: "아티초크", de: "Artischocke" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }], source: { en: "The Queen of Sauce 28 Fall, Year 1", zh: "酱料女皇 奇数年秋28日", zhTW: "醬料女皇 奇數年秋28日", ja: "ソースの女王 １年目 秋 28日", ko: "소스의 여왕 1년차 가을 28일", de: "Die Königin der Soßen 28. Herbst, Jahr 1" }, sourceCat: "tv", energy: 100, health: 45, buffs: [], buffDuration: null, sellPrice: 210 },
  { key: "autumns-bounty", icon: "Autumn's_Bounty.png", name: { en: "Autumn's Bounty", zh: "秋日恩赐", zhTW: "秋日恩賜", ja: "秋のめぐみ", ko: "가을의 수확", de: "Herbstfülle" }, ingredients: [{ key: "yam", name: { en: "Yam", zh: "山药", zhTW: "山藥", ja: "サツマイモ", ko: "참마", de: "Süßkartoffel" }, qty: 1 }, { key: "pumpkin", name: { en: "Pumpkin", zh: "南瓜", zhTW: "南瓜", ja: "カボチャ", ko: "호박", de: "Kürbis" }, qty: 1 }], source: { en: "Demetrius (Mail - 7+)", zh: "德米特里厄斯（邮件 - 7+）", zhTW: "德米特里厄斯（郵件 - 7+）", ja: "ディメトリウス（手紙 - 7+）", ko: "드미트리우스 (우편 - 7 이상)", de: "Demetrius (per Brief - 7+)" }, sourceCat: "friendship", energy: 220, health: 99, buffs: [{ type: "foraging", amount: 2 }, { type: "defense", amount: 2 }], buffDuration: "7m 41s", sellPrice: 350 },
  { key: "baked-fish", icon: "Baked_Fish.png", name: { en: "Baked Fish", zh: "烤鱼", zhTW: "烤魚", ja: "焼き魚", ko: "생선구이", de: "Gebackener Fisch" }, ingredients: [{ key: "sunfish", name: { en: "Sunfish", zh: "太阳鱼", zhTW: "太陽魚", ja: "ブルーギル", ko: "선피쉬", de: "Gotteslachs" }, qty: 1 }, { key: "bream", name: { en: "Bream", zh: "鲷鱼", zhTW: "鯛魚", ja: "ブリーム", ko: "도미", de: "Brasse" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }], source: { en: "The Queen of Sauce 7 Summer, Year 1", zh: "酱料女皇 奇数年夏季7日", zhTW: "醬料女皇 奇數年夏季7日", ja: "ソースの女王 １年目 夏 7日", ko: "소스의 여왕 1년차 여름 7일", de: "Die Königin der Soßen 7.Sommer, Jahr 1" }, sourceCat: "tv", energy: 75, health: 33, buffs: [], buffDuration: null, sellPrice: 100 },
  { key: "banana-pudding", icon: "Banana_Pudding.png", name: { en: "Banana Pudding", zh: "香蕉布丁", zhTW: "香蕉布丁", ja: "バナナプリン", ko: "바나나 푸딩", de: "Bananenpudding" }, ingredients: [{ key: "banana", name: { en: "Banana", zh: "香蕉", zhTW: "香蕉", ja: "バナナ", ko: "바나나", de: "Banane" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "Island Trader for Bone Fragment (30)", zh: "姜岛商人，消耗 骨头碎片（30）", zhTW: "姜島商人，消耗 骨頭碎片（30）", ja: "島のトレーダーから 骨の破片（30）", ko: "섬 상인에게 뼛조각 (30)를 주고 교환", de: "Inselhändler für Knochenfragment (30)" }, sourceCat: "shop", energy: 125, health: 56, buffs: [{ type: "mining", amount: 1 }, { type: "luck", amount: 1 }, { type: "defense", amount: 1 }], buffDuration: "5m 1s", sellPrice: 260 },
  { key: "bean-hotpot", icon: "Bean_Hotpot.png", name: { en: "Bean Hotpot", zh: "豆类火锅", zhTW: "豆類火鍋", ja: "マメのシチュー", ko: "콩 스튜", de: "Bohneneintopf" }, ingredients: [{ key: "green-bean", name: { en: "Green Bean", zh: "青豆", zhTW: "青豆", ja: "サヤエンドウ", ko: "완두콩", de: "Grüne Bohne" }, qty: 2 }], source: { en: "Clint (Mail - 7+)", zh: "克林特（邮件 - 7+）", zhTW: "克林特（郵件 - 7+）", ja: "クリント（手紙：7+）", ko: "클린트 (우편 - 7 이상)", de: "Clint (per Brief - 7+)" }, sourceCat: "friendship", energy: 125, health: 56, buffs: [{ type: "maxEnergy", amount: 30 }, { type: "magnetism", amount: 32 }], buffDuration: "7m", sellPrice: 100 },
  { key: "blackberry-cobbler", icon: "Blackberry_Cobbler.png", name: { en: "Blackberry Cobbler", zh: "黑莓脆皮饼", zhTW: "黑莓脆皮餅", ja: "ブラックベリーパイ", ko: "블랙베리 코블러", de: "Brombeer-Pastete" }, ingredients: [{ key: "blackberry", name: { en: "Blackberry", zh: "黑莓", zhTW: "黑莓", ja: "ブラックベリー", ko: "블랙베리", de: "Brombeere" }, qty: 2 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Fall, Year 2", zh: "酱料女皇 偶数年秋季14日", zhTW: "醬料女皇 偶數年秋季14日", ja: "ソースの女王 ２年目 秋 14日", ko: "소스의 여왕 2년차 가을 14일", de: "Die Königin der Soßen 14. Herbst, Jahr 2" }, sourceCat: "tv", energy: 175, health: 78, buffs: [], buffDuration: null, sellPrice: 260 },
  { key: "blueberry-tart", icon: "Blueberry_Tart.png", name: { en: "Blueberry Tart", zh: "蓝莓千层酥", zhTW: "藍莓千層酥", ja: "ブルーベリータルト", ko: "블루베리 타르트", de: "Blaubeertörtchen" }, ingredients: [{ key: "blueberry", name: { en: "Blueberry", zh: "蓝莓", zhTW: "藍莓", ja: "ブルーベリー", ko: "블루베리", de: "Blaubeere" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }], source: { en: "Pierre (Mail - 3+)", zh: "皮埃尔（邮件 - 3+）", zhTW: "皮埃爾（郵件 - 3+）", ja: "ピエール（手紙 - 3つ以上）", ko: "피에르 (우편 - 3 이상)", de: "Pierre (per Brief - 3+)" }, sourceCat: "friendship", energy: 125, health: 56, buffs: [], buffDuration: null, sellPrice: 150 },
  { key: "bread", icon: "Bread.png", name: { en: "Bread", zh: "面包", zhTW: "麵包", ja: "パン", ko: "빵", de: "Brot" }, ingredients: [{ key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }], source: { en: "The Queen of Sauce 28 Summer, Year 1 Stardrop Saloon for 100g", zh: "酱料女皇 奇数年夏28日 星之果实酒吧 价格100", zhTW: "醬料女皇 奇數年夏28日 星之果實酒吧 價格100", ja: "ソースの女王 １年目 夏 28日 スタードロップサルーンから120g", ko: "소스의 여왕 1년차 여름 28일 스타드롭 주점에서 100골드", de: "Die Königin der Soßen 28. Sommer, Jahr 1 Kneipe für 100 G" }, sourceCat: "tv", energy: 50, health: 22, buffs: [], buffDuration: null, sellPrice: 60 },
  { key: "bruschetta", icon: "Bruschetta.png", name: { en: "Bruschetta", zh: "意式烤面包", zhTW: "意式烤麵包", ja: "ブルスケッタ", ko: "브루쉐타", de: "Bruschetta" }, ingredients: [{ key: "bread", name: { en: "Bread", zh: "面包", zhTW: "麵包", ja: "パン", ko: "빵", de: "Brot" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }, { key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Winter, Year 2", zh: "酱料女皇 偶数年冬21日", zhTW: "醬料女皇 偶數年冬21日", ja: "ソースの女王 ２年目 冬 21日", ko: "소스의 여왕 2년차 겨울 21일", de: "Die Königin der Soßen 21. Winter, Jahr 2" }, sourceCat: "tv", energy: 113, health: 50, buffs: [], buffDuration: null, sellPrice: 210 },
  { key: "carp-surprise", icon: "Carp_Surprise.png", name: { en: "Carp Surprise", zh: "惊喜鲤鱼", zhTW: "驚喜鯉魚", ja: "コイのびっくり揚げ", ko: "깜짝잉어", de: "Karpfen-Überraschung" }, ingredients: [{ key: "carp", name: { en: "Carp", zh: "鲤鱼", zhTW: "鯉魚", ja: "コイ", ko: "잉어", de: "Karpfen" }, qty: 4 }], source: { en: "The Queen of Sauce 7 Summer, Year 2", zh: "酱料女皇 偶数年夏季7日", zhTW: "醬料女皇 偶數年夏季7日", ja: "ソースの女王 ２年目 夏 7日", ko: "소스의 여왕 2년차 여름 7일", de: "Die Königin der Soßen 7. Sommer, Jahr 2" }, sourceCat: "tv", energy: 90, health: 40, buffs: [], buffDuration: null, sellPrice: 150 },
  { key: "cheese-cauliflower", icon: "Cheese_Cauliflower.png", name: { en: "Cheese Cauliflower", zh: "乳酪花椰菜", zhTW: "乳酪花椰菜", ja: "カリフラワーのチーズ焼き", ko: "치즈 콜리플라워", de: "Überbackener Blumenkohl" }, ingredients: [{ key: "cauliflower", name: { en: "Cauliflower", zh: "花椰菜", zhTW: "花椰菜", ja: "カリフラワー", ko: "콜리플라워", de: "Blumenkohl" }, qty: 1 }, { key: "cheese", name: { en: "Cheese", zh: "奶酪", zhTW: "奶酪", ja: "チーズ", ko: "치즈", de: "Käse" }, qty: 1 }], source: { en: "Pam (Mail - 3+)", zh: "潘姆（邮件 - 3+）", zhTW: "潘姆（郵件 - 3+）", ja: "パム（手紙 - 3+）", ko: "팸 (우편 - 3 이상)", de: "Pam (per Brief - 3+)" }, sourceCat: "friendship", energy: 138, health: 62, buffs: [], buffDuration: null, sellPrice: 300 },
  { key: "chocolate-cake", icon: "Chocolate_Cake.png", name: { en: "Chocolate Cake", zh: "巧克力蛋糕", zhTW: "巧克力蛋糕", ja: "チョコレートケーキ", ko: "초콜릿 케이크", de: "Schokoladentorte" }, ingredients: [{ key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Winter, Year 1", zh: "酱料女皇 奇数年冬14日", zhTW: "醬料女皇 奇數年冬14日", ja: "ソースの女王 １年目 冬 14日", ko: "소스의 여왕 1년차 겨울 14일", de: "Die Königin der Soßen 14. Winter, Jahr 1" }, sourceCat: "tv", energy: 150, health: 67, buffs: [], buffDuration: null, sellPrice: 200 },
  { key: "chowder", icon: "Chowder.png", name: { en: "Chowder", zh: "海鲜杂烩汤", zhTW: "海鮮雜燴湯", ja: "クラムチャウダー", ko: "차우더", de: "Fischsuppe" }, ingredients: [{ key: "clam", name: { en: "Clam", zh: "蛤", zhTW: "蛤", ja: "アサリ", ko: "조개", de: "Venusmuschel" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }], source: { en: "Willy (Mail - 3+)", zh: "威利（邮件 - 3+）", zhTW: "威利（郵件 - 3+）", ja: "ウィリー（手紙：3+）", ko: "윌리 (우편 - 3 이상)", de: "Willy (per Brief - 3+)" }, sourceCat: "friendship", energy: 225, health: 101, buffs: [{ type: "fishing", amount: 1 }], buffDuration: "16m 47s", sellPrice: 135 },
  { key: "coleslaw", icon: "Coleslaw.png", name: { en: "Coleslaw", zh: "卷心菜沙拉", zhTW: "捲心菜沙拉", ja: "コールスロー", ko: "코울슬로", de: "Kohlsalat" }, ingredients: [{ key: "red-cabbage", name: { en: "Red Cabbage", zh: "红叶卷心菜", zhTW: "紅葉捲心菜", ja: "赤キャベツ", ko: "붉은 양배추", de: "Rotkohl" }, qty: 1 }, { key: "vinegar", name: { en: "Vinegar", zh: "醋", zhTW: "醋", ja: "酢", ko: "식초", de: "Essig" }, qty: 1 }, { key: "mayonnaise", name: { en: "Mayonnaise", zh: "蛋黄酱", zhTW: "蛋黃醬", ja: "マヨネーズ", ko: "마요네즈", de: "Mayonnaise" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Spring, Year 1", zh: "酱料女皇 奇数年春季14日", zhTW: "醬料女皇 奇數年春季14日", ja: "ソースの女王 １年目 春 14日", ko: "소스의 여왕 1년차 봄 14일", de: "Die Königin der Soßen 14. Frühling, Jahr 1" }, sourceCat: "tv", energy: 213, health: 95, buffs: [], buffDuration: null, sellPrice: 345 },
  { key: "complete-breakfast", icon: "Complete_Breakfast.png", name: { en: "Complete Breakfast", zh: "完美早餐", zhTW: "完美早餐", ja: "朝食セット", ko: "완벽한 아침", de: "Volles Frühstück" }, ingredients: [{ key: "fried-egg", name: { en: "Fried Egg", zh: "煎鸡蛋", zhTW: "煎雞蛋", ja: "目玉焼き", ko: "계란 프라이", de: "Spiegelei" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }, { key: "hashbrowns", name: { en: "Hashbrowns", zh: "薯饼", zhTW: "薯餅", ja: "ハッシュドポテト", ko: "해시브라운", de: "Kartoffelpuffer" }, qty: 1 }, { key: "pancakes", name: { en: "Pancakes", zh: "薄煎饼", zhTW: "薄煎餅", ja: "パンケーキ", ko: "팬케이크", de: "Pfannkuchen" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Spring, Year 2", zh: "酱料女皇 偶数年春季21日", zhTW: "醬料女皇 偶數年春季21日", ja: "ソースの女王 2年目 春 21日", ko: "소스의 여왕 2년차 봄 21일", de: "Die Königin der Soßen 21. Frühling, 2.Jahr" }, sourceCat: "tv", energy: 200, health: 90, buffs: [{ type: "farming", amount: 2 }, { type: "maxEnergy", amount: 50 }], buffDuration: "7m", sellPrice: 350 },
  { key: "cookie", icon: "Cookie.png", name: { en: "Cookie", zh: "饼干", zhTW: "餅乾", ja: "クッキー", ko: "쿠키", de: "Kekse" }, ingredients: [{ key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }], source: { en: "Evelyn (4-heart event)", zh: "艾芙琳（4）", zhTW: "艾芙琳（4）", ja: "エブリン（4）", ko: "에블린 (4 하트 이벤트)", de: "Evelyn (4)" }, sourceCat: "friendship", energy: 90, health: 40, buffs: [], buffDuration: null, sellPrice: 140 },
  { key: "crab-cakes", icon: "Crab_Cakes.png", name: { en: "Crab Cakes", zh: "蟹黄糕", zhTW: "蟹黃糕", ja: "クラブケーキ", ko: "게살 케이크", de: "Krabbenkuchen" }, ingredients: [{ key: "crab", name: { en: "Crab", zh: "螃蟹", zhTW: "螃蟹", ja: "カニ", ko: "게", de: "Krabbe" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Fall, Year 2", zh: "酱料女皇 偶数年秋季21日", zhTW: "醬料女皇 偶數年秋季21日", ja: "ソースの女王 偶数年,秋21日", ko: "소스의 여왕 2년차 가을 21일", de: "Die Königin der Soßen 21. Herbst, Jahr 2" }, sourceCat: "tv", energy: 225, health: 101, buffs: [{ type: "speed", amount: 1 }, { type: "defense", amount: 1 }], buffDuration: "16m 47s", sellPrice: 275 },
  { key: "cranberry-candy", icon: "Cranberry_Candy.png", name: { en: "Cranberry Candy", zh: "蔓越莓糖果", zhTW: "蔓越莓糖果", ja: "クランベリーキャンディ", ko: "크랜베리 캔디", de: "Preiselbeer-Süßigkeit" }, ingredients: [{ key: "cranberries", name: { en: "Cranberries", zh: "蔓越莓", zhTW: "蔓越莓", ja: "クランベリー", ko: "크랜베리", de: "Preiselbeere" }, qty: 1 }, { key: "apple", name: { en: "Apple", zh: "苹果", zhTW: "蘋果", ja: "リンゴ", ko: "사과", de: "Apfel" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "The Queen of Sauce 28 Winter, Year 1", zh: "酱料女皇 奇数年冬季28日", zhTW: "醬料女皇 奇數年冬季28日", ja: "ソースの女王 １年目 冬 28日", ko: "소스의 여왕 1년차 겨울 28일", de: "Die Königin der Soßen 28. Winter, Jahr 1" }, sourceCat: "tv", energy: 125, health: 56, buffs: [], buffDuration: null, sellPrice: 175 },
  { key: "cranberry-sauce", icon: "Cranberry_Sauce.png", name: { en: "Cranberry Sauce", zh: "红莓酱", zhTW: "紅莓醬", ja: "クランベリーソース", ko: "크랜베리 소스", de: "Preiselbeersoße" }, ingredients: [{ key: "cranberries", name: { en: "Cranberries", zh: "蔓越莓", zhTW: "蔓越莓", ja: "クランベリー", ko: "크랜베리", de: "Preiselbeere" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "Gus (Mail - 7+)", zh: "格斯（邮件 - 7+）", zhTW: "格斯（郵件 - 7+）", ja: "ガス（メール - 7+）", ko: "거스 (우편 - 7 이상)", de: "Gus (Per Brief - 7+)" }, sourceCat: "friendship", energy: 125, health: 56, buffs: [{ type: "mining", amount: 2 }], buffDuration: "3m 30s", sellPrice: 120 },
  { key: "crispy-bass", icon: "Crispy_Bass.png", name: { en: "Crispy Bass", zh: "香酥鲈鱼", zhTW: "香酥鱸魚", ja: "バスのサクサク揚げ", ko: "우럭 튀김", de: "Knuspriger Barsch" }, ingredients: [{ key: "largemouth-bass", name: { en: "Largemouth Bass", zh: "大嘴鲈鱼", zhTW: "大嘴鱸魚", ja: "ブラックバス", ko: "큰입우럭", de: "Forellenbarsch" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }], source: { en: "Kent (Mail - 3+)", zh: "肯特（信件 - 3+）", zhTW: "肯特（信件 - 3+）", ja: "ケント（手紙 - 3+）", ko: "켄트 (우편 - 3 이상)", de: "Kent (per Brief - 3+)" }, sourceCat: "friendship", energy: 90, health: 40, buffs: [{ type: "magnetism", amount: 64 }], buffDuration: "7m", sellPrice: 150 },
  { key: "dish-o-the-sea", icon: "Dish_O'_The_Sea.png", name: { en: "Dish O' The Sea", zh: "海之菜肴", zhTW: "海之菜餚", ja: "おさかな定食", ko: "바다의 요리", de: "Matrosenteller" }, ingredients: [{ key: "sardine", name: { en: "Sardine", zh: "沙丁鱼", zhTW: "沙丁魚", ja: "イワシ", ko: "정어리", de: "Sardine" }, qty: 2 }, { key: "hashbrowns", name: { en: "Hashbrowns", zh: "薯饼", zhTW: "薯餅", ja: "ハッシュドポテト", ko: "해시브라운", de: "Kartoffelpuffer" }, qty: 1 }], source: { en: "Fishing Level 3", zh: "钓鱼3级", zhTW: "釣魚3級", ja: "釣り レベル 3", ko: "낚시 레벨 3", de: "Fischen Stufe 3" }, sourceCat: "skill", energy: 150, health: 67, buffs: [{ type: "fishing", amount: 3 }], buffDuration: "5m 35s", sellPrice: 220 },
  { key: "eggplant-parmesan", icon: "Eggplant_Parmesan.png", name: { en: "Eggplant Parmesan", zh: "帕尔玛奶酪茄子", zhTW: "帕爾瑪奶酪茄子", ja: "ナスのチーズ焼き", ko: "가지 파마산", de: "Auberginen-Parmesan" }, ingredients: [{ key: "eggplant", name: { en: "Eggplant", zh: "茄子", zhTW: "茄子", ja: "ナス", ko: "가지", de: "Aubergine" }, qty: 1 }, { key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }], source: { en: "Lewis (Mail - 7+)", zh: "刘易斯（邮件 - 7+）", zhTW: "劉易斯（郵件 - 7+）", ja: "ルイス（手紙 - 7+）", ko: "루이스 (우편 - 7 이상)", de: "Lewis (per Brief - 7+)" }, sourceCat: "friendship", energy: 175, health: 78, buffs: [{ type: "mining", amount: 1 }, { type: "defense", amount: 3 }], buffDuration: "4m 39s", sellPrice: 200 },
  { key: "escargot", icon: "Escargot.png", name: { en: "Escargot", zh: "法式田螺", zhTW: "法式田螺", ja: "エスカルゴ", ko: "에스카르고", de: "Schneckengericht" }, ingredients: [{ key: "snail", name: { en: "Snail", zh: "蜗牛", zhTW: "蝸牛", ja: "カタツムリ", ko: "달팽이", de: "Schnecke" }, qty: 1 }, { key: "garlic", name: { en: "Garlic", zh: "蒜", zhTW: "蒜", ja: "ニンニク", ko: "마늘", de: "Knoblauch" }, qty: 1 }], source: { en: "Willy (Mail - 5+)", zh: "威利（邮件 - 5+）", zhTW: "威利（郵件 - 5+）", ja: "ウィリー（手紙 - 5つ以上）", ko: "윌리 (우편 - 5 이상)", de: "Willy (per Brief - 5+)" }, sourceCat: "friendship", energy: 225, health: 101, buffs: [{ type: "fishing", amount: 2 }], buffDuration: "16m 47s", sellPrice: 125 },
  { key: "farmers-lunch", icon: "Farmer's_Lunch.png", name: { en: "Farmer's Lunch", zh: "农夫午餐", zhTW: "農夫午餐", ja: "牧場主のランチ", ko: "농부의 점심", de: "Bauernmahlzeit" }, ingredients: [{ key: "omelet", name: { en: "Omelet", zh: "煎蛋卷", zhTW: "煎蛋卷", ja: "オムレツ", ko: "오믈렛", de: "Omelett" }, qty: 1 }, { key: "parsnip", name: { en: "Parsnip", zh: "防风草", zhTW: "防風草", ja: "パースニップ", ko: "파스닙", de: "Pastinake" }, qty: 1 }], source: { en: "Farming Level 3", zh: "耕种 3 级", zhTW: "耕種 3 級", ja: "農業 レベル 3", ko: "농사 레벨 3", de: "Hofarbeit Stufe 3" }, sourceCat: "skill", energy: 200, health: 90, buffs: [{ type: "farming", amount: 3 }], buffDuration: "5m 35s", sellPrice: 150 },
  { key: "fiddlehead-risotto", icon: "Fiddlehead_Risotto.png", name: { en: "Fiddlehead Risotto", zh: "意式蕨菜炖饭", zhTW: "意式蕨菜燉飯", ja: "フィドルヘッドのリゾット", ko: "청나래고사리 리조또", de: "Straußfarn-Risotto" }, ingredients: [{ key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }, { key: "fiddlehead-fern", name: { en: "Fiddlehead Fern", zh: "蕨菜", zhTW: "蕨菜", ja: "フィドルヘッド", ko: "청나래고사리", de: "Straußfarn" }, qty: 1 }, { key: "garlic", name: { en: "Garlic", zh: "蒜", zhTW: "蒜", ja: "ニンニク", ko: "마늘", de: "Knoblauch" }, qty: 1 }], source: { en: "The Queen of Sauce 28 Fall, Year 2", zh: "酱料女皇 偶数年秋28日", zhTW: "醬料女皇 偶數年秋28日", ja: "ソースの女王 ２年目 秋 28日", ko: "소스의 여왕 2년차 가을 28일", de: "Die Königin der Soßen 28. Herbst, Jahr 2" }, sourceCat: "tv", energy: 225, health: 101, buffs: [], buffDuration: null, sellPrice: 350 },
  { key: "fish-stew", icon: "Fish_Stew.png", name: { en: "Fish Stew", zh: "烩鱼汤", zhTW: "燴魚湯", ja: "魚のシチュー", ko: "생선 스튜", de: "Fischeintopf" }, ingredients: [{ key: "crayfish", name: { en: "Crayfish", zh: "小龙虾", zhTW: "小龍蝦", ja: "ザリガニ", ko: "민물가재", de: "Flusskrebs" }, qty: 1 }, { key: "mussel", name: { en: "Mussel", zh: "蚌", zhTW: "蚌", ja: "ムールガイ", ko: "홍합", de: "Miesmuschel" }, qty: 1 }, { key: "periwinkle", name: { en: "Periwinkle", zh: "玉黍螺", zhTW: "玉黍螺", ja: "タマキビ", ko: "충알고둥", de: "Strandschnecke" }, qty: 1 }, { key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }], source: { en: "Willy (Mail - 7+)", zh: "威利（邮件 - 7+）", zhTW: "威利（郵件 - 7+）", ja: "ウィリー（手紙 - 7+）", ko: "윌리 (우편 - 7 이상)", de: "Willy (per Brief - 7+)" }, sourceCat: "friendship", energy: 225, health: 101, buffs: [{ type: "fishing", amount: 3 }], buffDuration: "16m 47s", sellPrice: 175 },
  { key: "fish-taco", icon: "Fish_Taco.png", name: { en: "Fish Taco", zh: "鱼肉卷", zhTW: "魚肉卷", ja: "フィッシュタコス", ko: "생선 타코", de: "Fisch-Taco" }, ingredients: [{ key: "tuna", name: { en: "Tuna", zh: "金枪鱼", zhTW: "金槍魚", ja: "マグロ", ko: "참치", de: "Thunfisch" }, qty: 1 }, { key: "tortilla", name: { en: "Tortilla", zh: "墨西哥薄饼", zhTW: "墨西哥薄餅", ja: "トルティーヤ", ko: "또띠아", de: "Tortilla" }, qty: 1 }, { key: "red-cabbage", name: { en: "Red Cabbage", zh: "红叶卷心菜", zhTW: "紅葉捲心菜", ja: "赤キャベツ", ko: "붉은 양배추", de: "Rotkohl" }, qty: 1 }, { key: "mayonnaise", name: { en: "Mayonnaise", zh: "蛋黄酱", zhTW: "蛋黃醬", ja: "マヨネーズ", ko: "마요네즈", de: "Mayonnaise" }, qty: 1 }], source: { en: "Linus (Mail - 7+)", zh: "莱纳斯（邮件 - 7+）", zhTW: "萊納斯（郵件 - 7+）", ja: "ライナス（手紙 - 7つ以上）", ko: "라이너스 (우편 - 7 이상)", de: "Linus (per Brief - 7+)" }, sourceCat: "friendship", energy: 165, health: 74, buffs: [{ type: "fishing", amount: 2 }], buffDuration: "7m", sellPrice: 500 },
  { key: "fried-calamari", icon: "Fried_Calamari.png", name: { en: "Fried Calamari", zh: "炸鱿鱼", zhTW: "炸魷魚", ja: "イカフライ", ko: "오징어튀김", de: "Gebratener Tintenfisch" }, ingredients: [{ key: "squid", name: { en: "Squid", zh: "鱿鱼", zhTW: "魷魚", ja: "イカ", ko: "오징어", de: "Tintenfisch" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }], source: { en: "Jodi (Mail - 3+)", zh: "乔迪（邮件 - 3+）", zhTW: "喬迪（郵件 - 3+）", ja: "ジョディ（手紙 - 3+）", ko: "조디 (우편 - 3 이상)", de: "Jodi (Brief - 3+)" }, sourceCat: "friendship", energy: 80, health: 36, buffs: [], buffDuration: null, sellPrice: 150 },
  { key: "fried-eel", icon: "Fried_Eel.png", name: { en: "Fried Eel", zh: "炒鳗鱼", zhTW: "炒鰻魚", ja: "ウナギフライ", ko: "장어튀김", de: "Gebratener Aal" }, ingredients: [{ key: "eel", name: { en: "Eel", zh: "鳗鱼", zhTW: "鰻魚", ja: "ウナギ", ko: "장어", de: "Aal" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }], source: { en: "George (Mail - 3+)", zh: "乔治（邮件 - 3+）", zhTW: "喬治（郵件 - 3+）", ja: "ジョージ（手紙 - 3つ以上）", ko: "조지 (우편 - 3 이상)", de: "George (per Brief - 3+)" }, sourceCat: "friendship", energy: 75, health: 33, buffs: [{ type: "luck", amount: 1 }], buffDuration: "7m", sellPrice: 120 },
  { key: "fried-egg", icon: "Fried_Egg.png", name: { en: "Fried Egg", zh: "煎鸡蛋", zhTW: "煎雞蛋", ja: "目玉焼き", ko: "계란 프라이", de: "Spiegelei" }, ingredients: [{ key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }], source: { en: "Starter", zh: "初始拥有", zhTW: "初始擁有", ja: "増築後の家", ko: "농가 업그레이드", de: "1. Bauernhausausbau" }, sourceCat: "other", energy: 50, health: 22, buffs: [], buffDuration: null, sellPrice: 35 },
  { key: "fried-mushroom", icon: "Fried_Mushroom.png", name: { en: "Fried Mushroom", zh: "炒蘑菇", zhTW: "炒蘑菇", ja: "キノコいため", ko: "버섯구이", de: "Gebratene Pilze" }, ingredients: [{ key: "common-mushroom", name: { en: "Common Mushroom", zh: "普通蘑菇", zhTW: "普通蘑菇", ja: "マッシュルーム", ko: "흔한 버섯", de: "Gewöhnlicher Pilz" }, qty: 1 }, { key: "morel", name: { en: "Morel", zh: "羊肚菌", zhTW: "羊肚菌", ja: "アミガサタケ", ko: "곰보버섯", de: "Morchel" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }], source: { en: "Demetrius (Mail - 3+)", zh: "德米特里厄斯（邮件 - 3+）", zhTW: "德米特里厄斯（郵件 - 3+）", ja: "ディメトリウス（手紙 - 3+）", ko: "드미트리우스 (우편 - 3 이상)", de: "Demetrius (per Brief - 3+)" }, sourceCat: "friendship", energy: 135, health: 60, buffs: [{ type: "attack", amount: 2 }], buffDuration: "7m", sellPrice: 200 },
  { key: "fruit-salad", icon: "Fruit_Salad.png", name: { en: "Fruit Salad", zh: "水果沙拉", zhTW: "水果沙拉", ja: "フルーツサラダ", ko: "과일 샐러드", de: "Obstsalat" }, ingredients: [{ key: "blueberry", name: { en: "Blueberry", zh: "蓝莓", zhTW: "藍莓", ja: "ブルーベリー", ko: "블루베리", de: "Blaubeere" }, qty: 1 }, { key: "melon", name: { en: "Melon", zh: "甜瓜", zhTW: "甜瓜", ja: "メロン", ko: "멜론", de: "Melone" }, qty: 1 }, { key: "apricot", name: { en: "Apricot", zh: "杏子", zhTW: "杏子", ja: "アプリコット", ko: "살구", de: "Aprikose" }, qty: 1 }], source: { en: "The Queen of Sauce 7 Fall, Year 2", zh: "酱料女皇 偶数年秋7日", zhTW: "醬料女皇 偶數年秋7日", ja: "ソースの女王 ２年目 秋 7日", ko: "소스의 여왕 2년차 가을 7일", de: "Die Königin der Soßen 7. Herbst, Jahr 2" }, sourceCat: "tv", energy: 263, health: 118, buffs: [], buffDuration: null, sellPrice: 450 },
  { key: "ginger-ale", icon: "Ginger_Ale.png", name: { en: "Ginger Ale", zh: "姜汁汽水", zhTW: "薑汁汽水", ja: "ジンジャーエール", ko: "진저 에일", de: "Ginger Ale" }, ingredients: [{ key: "ginger", name: { en: "Ginger", zh: "姜", zhTW: "姜", ja: "ショウガ", ko: "생강", de: "Ingwer" }, qty: 3 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "Dwarf Shop in Volcano Dungeon for 1,000g", zh: "姜岛火山地牢商店 (1,000)", zhTW: "姜島火山地牢商店 (1,000)", ja: "ジンジャーアイランドの火山にあるドワーフショップ (1,000g)", ko: "진저 섬 화산의 드워프 가게 (1,000골드)", de: "Zwergenshop im Vulkan auf Ingwerinsel (1.000 G)" }, sourceCat: "shop", energy: 63, health: 28, buffs: [{ type: "luck", amount: 1 }], buffDuration: "5m", sellPrice: 200 },
  { key: "glazed-yams", icon: "Glazed_Yams.png", name: { en: "Glazed Yams", zh: "琉璃山药", zhTW: "琉璃山藥", ja: "サツマイモのミツがけ", ko: "맛탕", de: "Glasierte Süßkartoffeln" }, ingredients: [{ key: "yam", name: { en: "Yam", zh: "山药", zhTW: "山藥", ja: "サツマイモ", ko: "참마", de: "Süßkartoffel" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Fall, Year 1", zh: "酱料女皇 奇数年秋21日", zhTW: "醬料女皇 奇數年秋21日", ja: "ソースの女王 １年目 秋 21日", ko: "소스의 여왕 1년차 가을 21일", de: "Die Königin der Soßen 21. Herbst, Jahr 1" }, sourceCat: "tv", energy: 200, health: 90, buffs: [], buffDuration: null, sellPrice: 200 },
  { key: "hashbrowns", icon: "Hashbrowns.png", name: { en: "Hashbrowns", zh: "薯饼", zhTW: "薯餅", ja: "ハッシュドポテト", ko: "해시브라운", de: "Kartoffelpuffer" }, ingredients: [{ key: "potato", name: { en: "Potato", zh: "土豆", zhTW: "土豆", ja: "ジャガイモ", ko: "감자", de: "Kartoffel" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Spring, Year 2 Stardrop Saloon for 50g", zh: "酱料女皇 偶数年春季14日 星之果实酒吧 价格50", zhTW: "醬料女皇 偶數年春季14日 星之果實酒吧 價格50", ja: "ソースの女王 ２年目 春 14日 スタードロップサルーンから50g", ko: "소스의 여왕 2년차 봄 14일 스타드롭 주점에서 50골드", de: "Die Königin der Soßen 14. Frühling, Jahr 2 Kneipe für 250 G" }, sourceCat: "tv", energy: 90, health: 40, buffs: [{ type: "farming", amount: 1 }], buffDuration: "5m 35s", sellPrice: 120 },
  { key: "ice-cream", icon: "Ice_Cream.png", name: { en: "Ice Cream", zh: "冰淇淋", zhTW: "冰淇淋", ja: "アイスクリーム", ko: "아이스크림", de: "Eis" }, ingredients: [{ key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "Jodi (Mail - 7+)", zh: "乔迪（邮件 - 7+）", zhTW: "喬迪（郵件 - 7+）", ja: "ジョディ（手紙 - 7+）", ko: "조디 (우편 - 7 이상)", de: "Jodi (per Brief - 7+)" }, sourceCat: "friendship", energy: 100, health: 45, buffs: [], buffDuration: null, sellPrice: 120 },
  { key: "lobster-bisque", icon: "Lobster_Bisque.png", name: { en: "Lobster Bisque", zh: "龙虾浓汤", zhTW: "龍蝦濃湯", ja: "ロブスターのビスク", ko: "가재 비스크", de: "Hummer-Bisque" }, ingredients: [{ key: "lobster", name: { en: "Lobster", zh: "龙虾", zhTW: "龍蝦", ja: "ロブスター", ko: "바닷가재", de: "Hummer" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Winter, Year 2 Willy (Mail - 9+)", zh: "酱料女皇 偶数年冬季14日 威利（邮件 - 9+）", zhTW: "醬料女皇 偶數年冬季14日 威利（郵件 - 9+）", ja: "ソースの女王 ２年目 冬 14日 ウィリー（手紙：9+）", ko: "소스의 여왕 2년차 겨울 14일 윌리 (우편 - 9 이상)", de: "Die Königin der Soßen 14. Winter, Jahr 2 Willy (per Brief - 9+)" }, sourceCat: "tv", energy: 225, health: 101, buffs: [{ type: "fishing", amount: 3 }, { type: "maxEnergy", amount: 50 }], buffDuration: "16m 47s", sellPrice: 205 },
  { key: "lucky-lunch", icon: "Lucky_Lunch.png", name: { en: "Lucky Lunch", zh: "幸运午餐", zhTW: "幸運午餐", ja: "ラッキーランチ", ko: "행운의 점심", de: "Glücksmahlzeit" }, ingredients: [{ key: "sea-cucumber", name: { en: "Sea Cucumber", zh: "海参", zhTW: "海參", ja: "ナマコ", ko: "해삼", de: "Seegurke" }, qty: 1 }, { key: "tortilla", name: { en: "Tortilla", zh: "墨西哥薄饼", zhTW: "墨西哥薄餅", ja: "トルティーヤ", ko: "또띠아", de: "Tortilla" }, qty: 1 }, { key: "blue-jazz", name: { en: "Blue Jazz", zh: "蓝爵", zhTW: "藍爵", ja: "ブルージャズ", ko: "푸른 재즈", de: "Blaue Jazz" }, qty: 1 }], source: { en: "The Queen of Sauce 28 Spring, Year 2", zh: "酱料女皇 偶数年春28日", zhTW: "醬料女皇 偶數年春28日", ja: "ソースの女王 ２年目 春 28日", ko: "소스의 여왕 2년차 봄 28일", de: "Die Königin der Soßen 28. Frühling, Jahr 2" }, sourceCat: "tv", energy: 100, health: 45, buffs: [{ type: "luck", amount: 3 }], buffDuration: "11m 11s", sellPrice: 250 },
  { key: "maki-roll", icon: "Maki_Roll.png", name: { en: "Maki Roll", zh: "生鱼寿司", zhTW: "生魚壽司", ja: "巻きずし", ko: "마키 롤", de: "Maki-Rolle" }, ingredients: [{ key: "seaweed", name: { en: "Seaweed", zh: "海草", zhTW: "海草", ja: "海草", ko: "해초", de: "Seetang" }, qty: 1 }, { key: "rice", name: { en: "Rice", zh: "大米", zhTW: "大米", ja: "米", ko: "쌀", de: "Reis" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Summer, Year 1 Stardrop Saloon for 300g", zh: "酱料女皇 奇数年夏季21日 星之果实酒吧 购买 300", zhTW: "醬料女皇 奇數年夏季21日 星之果實酒吧 購買 300", ja: "ソースの女王 １年目 夏 21日 スタードロップサルーンから300g", ko: "소스의 여왕 1년차 여름 21일 스타드롭 주점에서 300골드", de: "Die Königin der Soßen 21. Sommer, Jahr 1 Kneipe für 300 G" }, sourceCat: "tv", energy: 100, health: 45, buffs: [], buffDuration: null, sellPrice: 220 },
  { key: "mango-sticky-rice", icon: "Mango_Sticky_Rice.png", name: { en: "Mango Sticky Rice", zh: "芒果糯米饭", zhTW: "芒果糯米飯", ja: "マンゴーライス", ko: "카오 니야우 마무앙", de: "Mango Klebreis" }, ingredients: [{ key: "mango", name: { en: "Mango", zh: "芒果", zhTW: "芒果", ja: "マンゴー", ko: "망고", de: "Mango" }, qty: 1 }, { key: "coconut", name: { en: "Coconut", zh: "椰子", zhTW: "椰子", ja: "ココナッツ", ko: "코코넛", de: "Kokosnuss" }, qty: 1 }, { key: "rice", name: { en: "Rice", zh: "大米", zhTW: "大米", ja: "米", ko: "쌀", de: "Reis" }, qty: 1 }], source: { en: "Leo (Mail - 7+)", zh: "雷欧（邮件 - 7+）", zhTW: "雷歐（郵件 - 7+）", ja: "レオ（手紙 - 7+）", ko: "레오 ( 7 이상일 때 우편)", de: "Leo (per Brief - 7+)" }, sourceCat: "friendship", energy: 113, health: 50, buffs: [{ type: "defense", amount: 3 }], buffDuration: "5m 1s", sellPrice: 250 },
  { key: "maple-bar", icon: "Maple_Bar.png", name: { en: "Maple Bar", zh: "枫糖棒", zhTW: "楓糖棒", ja: "メープルバー", ko: "메이플 바", de: "Ahornriegel" }, ingredients: [{ key: "maple-syrup", name: { en: "Maple Syrup", zh: "枫糖浆", zhTW: "楓糖漿", ja: "メープルシロップ", ko: "메이플 시럽", de: "Ahornsirup" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Summer, Year 2", zh: "酱料女皇 偶数年夏季14日", zhTW: "醬料女皇 偶數年夏季14日", ja: "ソースの女王 ２年目 夏 14日", ko: "소스의 여왕 2년차 여름 14일", de: "Die Königin der Soßen 14. Sommer, Jahr 2" }, sourceCat: "tv", energy: 225, health: 101, buffs: [{ type: "farming", amount: 1 }, { type: "fishing", amount: 1 }, { type: "mining", amount: 1 }], buffDuration: "16m 47s", sellPrice: 300 },
  { key: "miners-treat", icon: "Miner's_Treat.png", name: { en: "Miner's Treat", zh: "矿工特供", zhTW: "礦工特供", ja: "マインキャンディ", ko: "광부의 간식", de: "Bergarbeiter-Leckerbissen" }, ingredients: [{ key: "cave-carrot", name: { en: "Cave Carrot", zh: "山洞萝卜", zhTW: "山洞蘿蔔", ja: "洞窟ニンジン", ko: "동굴 당근", de: "Höhlenkarotte" }, qty: 2 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }], source: { en: "Mining Level 3", zh: "采矿3级", zhTW: "採礦3級", ja: "採鉱 レベル3", ko: "채광 레벨 3", de: "Minenarbeit Stufe 3" }, sourceCat: "skill", energy: 125, health: 56, buffs: [{ type: "mining", amount: 3 }, { type: "magnetism", amount: 32 }], buffDuration: "5m 35s", sellPrice: 200 },
  { key: "omelet", icon: "Omelet.png", name: { en: "Omelet", zh: "煎蛋卷", zhTW: "煎蛋卷", ja: "オムレツ", ko: "오믈렛", de: "Omelett" }, ingredients: [{ key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }], source: { en: "The Queen of Sauce 28 Spring, Year 1 Stardrop Saloon for 100g", zh: "酱料女皇 奇数年春季28日 在星之果实酒吧花100购买", zhTW: "醬料女皇 奇數年春季28日 在星之果實酒吧花100購買", ja: "ソースの女王 １年目 春 28日 スタードロップサルーンから100g", ko: "소스의 여왕 1년째, 봄의 28일째 스타드롭 주점에서 100골드", de: "Die Königin der Soßen 28. Frühling, Jahr 1 Kneipe für 500 G" }, sourceCat: "tv", energy: 100, health: 45, buffs: [], buffDuration: null, sellPrice: 125 },
  { key: "pale-broth", icon: "Pale_Broth.png", name: { en: "Pale Broth", zh: "清汤", zhTW: "清湯", ja: "澄んだスープ", ko: "창백한 죽", de: "Bleiche Brühe" }, ingredients: [{ key: "white-algae", name: { en: "White Algae", zh: "白藻", zhTW: "白藻", ja: "白い藻", ko: "흰 조류", de: "Weißalge" }, qty: 2 }], source: { en: "Marnie (Mail - 3+)", zh: "玛妮（邮件 - 3+）", zhTW: "瑪妮（郵件 - 3+）", ja: "マーニー（手紙 - 3+）", ko: "마니 (우편 - 3 이상)", de: "Marnie (per Brief - 3+)" }, sourceCat: "friendship", energy: 125, health: 56, buffs: [], buffDuration: null, sellPrice: 150 },
  { key: "pancakes", icon: "Pancakes.png", name: { en: "Pancakes", zh: "薄煎饼", zhTW: "薄煎餅", ja: "パンケーキ", ko: "팬케이크", de: "Pfannkuchen" }, ingredients: [{ key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Summer, Year 1 Stardrop Saloon for 100g", zh: "酱料女皇 奇数年夏季14日 星之果实酒吧价格为100", zhTW: "醬料女皇 奇數年夏季14日 星之果實酒吧價格為100", ja: "ソースの女王 １年目 夏 14日 スタードロップサルーンから100g", ko: "소스의 여왕 1년차 여름 14일 스타드롭 주점에서 100골드", de: "Die Königin der Soßen 14. Sommer, Jahr 1 Kneipe für 100 G" }, sourceCat: "tv", energy: 90, health: 40, buffs: [{ type: "foraging", amount: 2 }], buffDuration: "11m 11s", sellPrice: 80 },
  { key: "parsnip-soup", icon: "Parsnip_Soup.png", name: { en: "Parsnip Soup", zh: "防风草汤", zhTW: "防風草湯", ja: "パースニップのスープ", ko: "설탕당근 스프", de: "Pastinakensuppe" }, ingredients: [{ key: "parsnip", name: { en: "Parsnip", zh: "防风草", zhTW: "防風草", ja: "パースニップ", ko: "파스닙", de: "Pastinake" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }, { key: "vinegar", name: { en: "Vinegar", zh: "醋", zhTW: "醋", ja: "酢", ko: "식초", de: "Essig" }, qty: 1 }], source: { en: "Caroline (Mail - 3+)", zh: "卡洛琳（邮件 - 3+）", zhTW: "卡洛琳（郵件 - 3+）", ja: "キャロライン（手紙 - 3+）", ko: "캐롤라인 (우편 - 3 이상)", de: "Caroline (Brief - 3+)" }, sourceCat: "friendship", energy: 85, health: 38, buffs: [], buffDuration: null, sellPrice: 120 },
  { key: "pepper-poppers", icon: "Pepper_Poppers.png", name: { en: "Pepper Poppers", zh: "爆炒青椒", zhTW: "爆炒青椒", ja: "揚げトウガラシ", ko: "페퍼 파퍼", de: "Paprika-Popper" }, ingredients: [{ key: "hot-pepper", name: { en: "Hot Pepper", zh: "辣椒", zhTW: "辣椒", ja: "トウガラシ", ko: "매운 고추", de: "Peperoni" }, qty: 1 }, { key: "cheese", name: { en: "Cheese", zh: "奶酪", zhTW: "奶酪", ja: "チーズ", ko: "치즈", de: "Käse" }, qty: 1 }], source: { en: "Shane (Mail - 3+)", zh: "谢恩（信件 - 3+）", zhTW: "謝恩（信件 - 3+）", ja: "シェーン（手紙 - 3+）", ko: "셰인 (우편 - 3 이상)", de: "Shane (per Brief - 3+)" }, sourceCat: "friendship", energy: 130, health: 58, buffs: [{ type: "farming", amount: 2 }, { type: "speed", amount: 1 }], buffDuration: "7m", sellPrice: 200 },
  { key: "pink-cake", icon: "Pink_Cake.png", name: { en: "Pink Cake", zh: "粉红蛋糕", zhTW: "粉紅蛋糕", ja: "ピンクケーキ", ko: "핑크 케이크", de: "Pinke Torte" }, ingredients: [{ key: "melon", name: { en: "Melon", zh: "甜瓜", zhTW: "甜瓜", ja: "メロン", ko: "멜론", de: "Melone" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "egg", name: { en: "Egg", zh: "蛋", zhTW: "蛋", ja: "タマゴ", ko: "달걀", de: "Ei" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Summer, Year 2", zh: "酱料女皇 偶数年夏季21日", zhTW: "醬料女皇 偶數年夏季21日", ja: "ソースの女王 夏 21日（2年目）", ko: "소스의 여왕 2년차 여름 21일", de: "Die Königin der Soßen 21. Sommer, Jahr 2" }, sourceCat: "tv", energy: 250, health: 112, buffs: [], buffDuration: null, sellPrice: 480 },
  { key: "pizza", icon: "Pizza.png", name: { en: "Pizza", zh: "披萨", zhTW: "披薩", ja: "ピザ", ko: "피자", de: "Pizza" }, ingredients: [{ key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }, { key: "cheese", name: { en: "Cheese", zh: "奶酪", zhTW: "奶酪", ja: "チーズ", ko: "치즈", de: "Käse" }, qty: 1 }], source: { en: "The Queen of Sauce 7 Spring, Year 2 Stardrop Saloon for 150g", zh: "酱料女皇 偶数年春季7日 星之果实酒吧购买 150", zhTW: "醬料女皇 偶數年春季7日 星之果實酒吧購買 150", ja: "ソースの女王 ２年目 春 7日 スタードロップサルーンから150g", ko: "소스의 여왕 2년차 봄 7일 스타드롭 주점에서 150골드", de: "Die Königin der Soßen 7. Tag des Frühlings, Jahr 2 Kneipe für 150 G" }, sourceCat: "tv", energy: 150, health: 67, buffs: [], buffDuration: null, sellPrice: 300 },
  { key: "plum-pudding", icon: "Plum_Pudding.png", name: { en: "Plum Pudding", zh: "葡萄干布丁", zhTW: "葡萄乾布丁", ja: "プラムのプディング", ko: "자두 푸딩", de: "Plumpudding" }, ingredients: [{ key: "wild-plum", name: { en: "Wild Plum", zh: "野梅", zhTW: "野梅", ja: "野生のプラム", ko: "야생 자두", de: "Wildpflaume" }, qty: 2 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "The Queen of Sauce 7 Winter, Year 1", zh: "酱料女皇 奇数年冬季7日", zhTW: "醬料女皇 奇數年冬季7日", ja: "ソースの女王 １年目 冬 7日", ko: "소스의 여왕 1년차 겨울 7일", de: "Die Königin der Soßen 7. Winter, Jahr 1" }, sourceCat: "tv", energy: 175, health: 78, buffs: [], buffDuration: null, sellPrice: 260 },
  { key: "poi", icon: "Poi.png", name: { en: "Poi", zh: "夏威夷芋泥", zhTW: "夏威夷芋泥", ja: "ポイ", ko: "포이", de: "Poi" }, ingredients: [{ key: "taro-root", name: { en: "Taro Root", zh: "芋头", zhTW: "芋頭", ja: "タロイモの根", ko: "토란", de: "Taro-Wurzel" }, qty: 4 }], source: { en: "Leo (Mail - 3+)", zh: "雷欧（邮件 - 3+）", zhTW: "雷歐（郵件 - 3+）", ja: "レオ（手紙：3+）", ko: "레오 (우편 - 3 이상)", de: "Leo (Brief - 3+)" }, sourceCat: "friendship", energy: 75, health: 33, buffs: [], buffDuration: null, sellPrice: 400 },
  { key: "poppyseed-muffin", icon: "Poppyseed_Muffin.png", name: { en: "Poppyseed Muffin", zh: "虞美人籽松糕", zhTW: "虞美人籽松糕", ja: "ポピーシードマフィン", ko: "양귀비씨 머핀", de: "Mohnmuffin" }, ingredients: [{ key: "poppy", name: { en: "Poppy", zh: "虞美人花", zhTW: "虞美人花", ja: "ポピー", ko: "양귀비", de: "Mohn" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "The Queen of Sauce 7 Winter, Year 2", zh: "酱料女皇 偶数年冬7日", zhTW: "醬料女皇 偶數年冬7日", ja: "ソースの女王 ２年目 冬 7日", ko: "소스의 여왕 2년차 겨울 7일", de: "Die Königin der Soßen 7. Winter, Jahr 2" }, sourceCat: "tv", energy: 150, health: 67, buffs: [], buffDuration: null, sellPrice: 250 },
  { key: "pumpkin-pie", icon: "Pumpkin_Pie.png", name: { en: "Pumpkin Pie", zh: "南瓜派", zhTW: "南瓜派", ja: "パンプキンパイ", ko: "호박 파이", de: "Kürbiskuchen" }, ingredients: [{ key: "pumpkin", name: { en: "Pumpkin", zh: "南瓜", zhTW: "南瓜", ja: "カボチャ", ko: "호박", de: "Kürbis" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Winter, Year 1", zh: "酱料女皇 奇数年冬21日", zhTW: "醬料女皇 奇數年冬21日", ja: "ソースの女王 １年目 冬 21日", ko: "소스의 여왕 1년차 겨울 21일", de: "Die Königin der Soßen 21. Winter, Jahr 1" }, sourceCat: "tv", energy: 225, health: 101, buffs: [], buffDuration: null, sellPrice: 385 },
  { key: "pumpkin-soup", icon: "Pumpkin_Soup.png", name: { en: "Pumpkin Soup", zh: "南瓜汤", zhTW: "南瓜湯", ja: "カボチャのスープ", ko: "호박죽", de: "Kürbissuppe" }, ingredients: [{ key: "pumpkin", name: { en: "Pumpkin", zh: "南瓜", zhTW: "南瓜", ja: "カボチャ", ko: "호박", de: "Kürbis" }, qty: 1 }, { key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }], source: { en: "Robin (Mail - 7+)", zh: "罗宾（邮件 - 7+）", zhTW: "羅賓（郵件 - 7+）", ja: "ロビン（手紙 - 7つ以上）", ko: "로빈 (우편 - 7 이상)", de: "Robin (per Brief - 7+)" }, sourceCat: "friendship", energy: 200, health: 90, buffs: [{ type: "defense", amount: 2 }, { type: "luck", amount: 2 }], buffDuration: "7m 41s", sellPrice: 300 },
  { key: "radish-salad", icon: "Radish_Salad.png", name: { en: "Radish Salad", zh: "萝卜沙拉", zhTW: "蘿蔔沙拉", ja: "ラディッシュサラダ", ko: "무 샐러드", de: "Radieschensalat" }, ingredients: [{ key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }, { key: "vinegar", name: { en: "Vinegar", zh: "醋", zhTW: "醋", ja: "酢", ko: "식초", de: "Essig" }, qty: 1 }, { key: "radish", name: { en: "Radish", zh: "萝卜", zhTW: "蘿蔔", ja: "ラディッシュ", ko: "무", de: "Radieschen" }, qty: 1 }], source: { en: "The Queen of Sauce 21 Spring, Year 1", zh: "酱料女皇 奇数年春21日", zhTW: "醬料女皇 奇數年春21日", ja: "ソースの女王 １年目 春 21日", ko: "소스의 여왕 1년차 봄 21일", de: "Die Königin der Soßen 21. Frühling, Jahr 1" }, sourceCat: "tv", energy: 200, health: 90, buffs: [], buffDuration: null, sellPrice: 300 },
  { key: "red-plate", icon: "Red_Plate.png", name: { en: "Red Plate", zh: "红之盛宴", zhTW: "紅之盛宴", ja: "レッドサラダ", ko: "붉은 정식", de: "Rote Platte" }, ingredients: [{ key: "red-cabbage", name: { en: "Red Cabbage", zh: "红叶卷心菜", zhTW: "紅葉捲心菜", ja: "赤キャベツ", ko: "붉은 양배추", de: "Rotkohl" }, qty: 1 }, { key: "radish", name: { en: "Radish", zh: "萝卜", zhTW: "蘿蔔", ja: "ラディッシュ", ko: "무", de: "Radieschen" }, qty: 1 }], source: { en: "Emily (Mail - 7+)", zh: "艾米丽（邮件 - 7+）", zhTW: "艾米麗（郵件 - 7+）", ja: "エミリー（手紙 - 7つ以上）", ko: "에밀리 (우편 - 7 이상)", de: "Emily (per Brief - 7+)" }, sourceCat: "friendship", energy: 240, health: 108, buffs: [{ type: "maxEnergy", amount: 50 }], buffDuration: "3m 30s", sellPrice: 400 },
  { key: "rhubarb-pie", icon: "Rhubarb_Pie.png", name: { en: "Rhubarb Pie", zh: "大黄派", zhTW: "大黃派", ja: "ルバーブのパイ", ko: "대황 파이", de: "Rhabarberkuchen" }, ingredients: [{ key: "rhubarb", name: { en: "Rhubarb", zh: "大黄", zhTW: "大黃", ja: "ルバーブ", ko: "대황", de: "Rhabarber" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }], source: { en: "Marnie (Mail - 7+)", zh: "玛妮（邮件 - 7+）", zhTW: "瑪妮（郵件 - 7+）", ja: "マーニー（手紙 - 7+）", ko: "마니 (우편 - 7 이상)", de: "Marnie (per Brief - 7+)" }, sourceCat: "friendship", energy: 215, health: 96, buffs: [], buffDuration: null, sellPrice: 400 },
  { key: "rice-pudding", icon: "Rice_Pudding.png", name: { en: "Rice Pudding", zh: "大米布丁", zhTW: "大米布丁", ja: "ライスプディング", ko: "라이스 푸딩", de: "Milchreis" }, ingredients: [{ key: "milk", name: { en: "Milk", zh: "牛奶", zhTW: "牛奶", ja: "ミルク", ko: "우유", de: "Milch" }, qty: 1 }, { key: "sugar", name: { en: "Sugar", zh: "糖", zhTW: "糖", ja: "砂糖", ko: "설탕", de: "Zucker" }, qty: 1 }, { key: "rice", name: { en: "Rice", zh: "大米", zhTW: "大米", ja: "米", ko: "쌀", de: "Reis" }, qty: 1 }], source: { en: "Evelyn (Mail - 7+)", zh: "艾芙琳（邮件 - 7+）", zhTW: "艾芙琳（郵件 - 7+）", ja: "エブリン（手紙 - 7+）", ko: "에블린 (우편 - 7 이상)", de: "Evelyn (per Brief - 7+)" }, sourceCat: "friendship", energy: 115, health: 51, buffs: [], buffDuration: null, sellPrice: 260 },
  { key: "roasted-hazelnuts", icon: "Roasted_Hazelnuts.png", name: { en: "Roasted Hazelnuts", zh: "烤榛子", zhTW: "烤榛子", ja: "焼きヘーゼルナッツ", ko: "구운 헤이즐넛", de: "Geröstete Haselnüsse" }, ingredients: [{ key: "hazelnut", name: { en: "Hazelnut", zh: "榛子", zhTW: "榛子", ja: "ヘーゼルナッツ", ko: "헤이즐넛", de: "Haselnuss" }, qty: 3 }], source: { en: "The Queen of Sauce 28 Summer, Year 2", zh: "酱料女皇 偶数年夏28日", zhTW: "醬料女皇 偶數年夏28日", ja: "ソースの女王 ２年目 夏 28日", ko: "소스의 여왕 2년차 여름 28일", de: "Die Königin der Soßen 28. Sommer, Jahr 2" }, sourceCat: "tv", energy: 175, health: 78, buffs: [], buffDuration: null, sellPrice: 270 },
  { key: "roots-platter", icon: "Roots_Platter.png", name: { en: "Roots Platter", zh: "块茎拼盘", zhTW: "塊莖拼盤", ja: "根菜盛り", ko: "뿌리채소 모음", de: "Wurzelplatte" }, ingredients: [{ key: "cave-carrot", name: { en: "Cave Carrot", zh: "山洞萝卜", zhTW: "山洞蘿蔔", ja: "洞窟ニンジン", ko: "동굴 당근", de: "Höhlenkarotte" }, qty: 1 }, { key: "winter-root", name: { en: "Winter Root", zh: "冬根", zhTW: "冬根", ja: "クワイ", ko: "겨울뿌리", de: "Winterwurzel" }, qty: 1 }], source: { en: "Combat Level 3", zh: "战斗3级", zhTW: "戰鬥3級", ja: "戦闘 レベル 3", ko: "전투 레벨 3", de: "Kampf Stufe 3" }, sourceCat: "skill", energy: 125, health: 56, buffs: [{ type: "attack", amount: 3 }], buffDuration: "5m 35s", sellPrice: 100 },
  { key: "salad", icon: "Salad.png", name: { en: "Salad", zh: "沙拉", zhTW: "沙拉", ja: "サラダ", ko: "샐러드", de: "Salat" }, ingredients: [{ key: "leek", name: { en: "Leek", zh: "韭葱", zhTW: "韭蔥", ja: "ポロネギ", ko: "리크", de: "Lauch" }, qty: 1 }, { key: "dandelion", name: { en: "Dandelion", zh: "蒲公英", zhTW: "蒲公英", ja: "タンポポ", ko: "민들레", de: "Löwenzahn" }, qty: 1 }, { key: "vinegar", name: { en: "Vinegar", zh: "醋", zhTW: "醋", ja: "酢", ko: "식초", de: "Essig" }, qty: 1 }], source: { en: "Emily (Mail - 3+)", zh: "艾米丽（邮件 - 3+）", zhTW: "艾米麗（郵件 - 3+）", ja: "エミリー（手紙 - 3+）", ko: "에밀리 (우편 - 3 이상)", de: "Emily (per Brief - 3+)" }, sourceCat: "friendship", energy: 113, health: 50, buffs: [], buffDuration: null, sellPrice: 110 },
  { key: "salmon-dinner", icon: "Salmon_Dinner.png", name: { en: "Salmon Dinner", zh: "鲑鱼晚餐", zhTW: "鮭魚晚餐", ja: "サーモンディナー", ko: "연어 정찬", de: "Lachs-Mahlzeit" }, ingredients: [{ key: "salmon", name: { en: "Salmon", zh: "鲑鱼", zhTW: "鮭魚", ja: "サケ", ko: "연어", de: "Lachs" }, qty: 1 }, { key: "amaranth", name: { en: "Amaranth", zh: "苋菜", zhTW: "莧菜", ja: "アマランサス", ko: "아마란스", de: "Amarant" }, qty: 1 }, { key: "kale", name: { en: "Kale", zh: "甘蓝菜", zhTW: "甘藍菜", ja: "ケール", ko: "케일", de: "Grünkohl" }, qty: 1 }], source: { en: "Gus (Mail - 3+)", zh: "格斯（邮件 - 3+）", zhTW: "格斯（郵件 - 3+）", ja: "ガス（手紙 - 3+）", ko: "거스 (우편 - 3 이상)", de: "Gus (per Brief - 3+)" }, sourceCat: "friendship", energy: 125, health: 56, buffs: [], buffDuration: null, sellPrice: 300 },
  { key: "sashimi", icon: "Sashimi.png", name: { en: "Sashimi", zh: "生鱼片", zhTW: "生魚片", ja: "刺し身", ko: "회", de: "Sashimi" }, ingredients: [{ key: "fish", name: { en: "Any Fish", zh: "任意鱼", zhTW: "任意魚", ja: "魚", ko: "아무 생선", de: "Jeder Fisch" }, qty: 1 }], source: { en: "Linus (Mail - 3+)", zh: "莱纳斯（邮件 - 3+）", zhTW: "萊納斯（郵件 - 3+）", ja: "ライナス（手紙 - 3つ以上）", ko: "라이너스 (우편 - 3 이상)", de: "Linus (per Brief - 3+)" }, sourceCat: "friendship", energy: 75, health: 33, buffs: [], buffDuration: null, sellPrice: 75 },
  { key: "seafoam-pudding", icon: "Seafoam_Pudding.png", name: { en: "Seafoam Pudding", zh: "海泡布丁", zhTW: "海泡布丁", ja: "海の泡プリン", ko: "바다 거품 푸딩", de: "Meerschaumpudding" }, ingredients: [{ key: "flounder", name: { en: "Flounder", zh: "比目鱼", zhTW: "比目魚", ja: "平らな魚", ko: "가자미", de: "Flunder" }, qty: 1 }, { key: "midnight-carp", name: { en: "Midnight Carp", zh: "午夜鲤鱼", zhTW: "午夜鯉魚", ja: "シャイなコイ", ko: "자정 잉어", de: "Mitternachtskarpfen" }, qty: 1 }, { key: "squid-ink", name: { en: "Squid Ink", zh: "鱿鱼墨汁", zhTW: "魷魚墨汁", ja: "イカのインク", ko: "오징어 먹물", de: "Tintenfisch Tinte" }, qty: 1 }], source: { en: "Fishing Level 9", zh: "钓鱼（9级）", zhTW: "釣魚（9級）", ja: "釣り（レベル9）", ko: "낚시 (레벨 9)", de: "Fischen (Level 9)" }, sourceCat: "skill", energy: 175, health: 78, buffs: [{ type: "fishing", amount: 4 }], buffDuration: "3m 30s", sellPrice: 300 },
  { key: "shrimp-cocktail", icon: "Shrimp_Cocktail.png", name: { en: "Shrimp Cocktail", zh: "虾鸡尾酒", zhTW: "蝦雞尾酒", ja: "エビのカクテル", ko: "새우 칵테일", de: "Krabbencocktail" }, ingredients: [{ key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }, { key: "shrimp", name: { en: "Shrimp", zh: "虾", zhTW: "蝦", ja: "エビ", ko: "새우", de: "Garnele" }, qty: 1 }, { key: "wild-horseradish", name: { en: "Wild Horseradish", zh: "野山葵", zhTW: "野山葵", ja: "ノワサビ", ko: "야생 고추냉이", de: "Wilder Meerrettich" }, qty: 1 }], source: { en: "The Queen of Sauce 28 Winter, Year 2", zh: "酱料女皇 偶数年冬28日", zhTW: "醬料女皇 偶數年冬28日", ja: "ソースの女王 冬 28日（2年目）", ko: "소스의 여왕 2년차 겨울 28일", de: "Die Königin der Soßen 28 Winter, Jahr 2" }, sourceCat: "tv", energy: 225, health: 101, buffs: [{ type: "fishing", amount: 1 }, { type: "luck", amount: 1 }], buffDuration: "10m 2s", sellPrice: 160 },
  { key: "spaghetti", icon: "Spaghetti.png", name: { en: "Spaghetti", zh: "意大利面", zhTW: "意大利麵", ja: "スパゲッティ", ko: "스파게티", de: "Spaghetti" }, ingredients: [{ key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }], source: { en: "Lewis (Mail - 3+)", zh: "刘易斯（邮件 - 3+）", zhTW: "劉易斯（郵件 - 3+）", ja: "ルイス（手紙 - 3+）", ko: "루이스 (우편 - 3 이상)", de: "Lewis (per Brief - 3+)" }, sourceCat: "friendship", energy: 75, health: 33, buffs: [], buffDuration: null, sellPrice: 120 },
  { key: "spicy-eel", icon: "Spicy_Eel.png", name: { en: "Spicy Eel", zh: "香辣鳗鱼", zhTW: "香辣鰻魚", ja: "ピリ辛ウナギ", ko: "매콤한 장어", de: "Würziger Aal" }, ingredients: [{ key: "eel", name: { en: "Eel", zh: "鳗鱼", zhTW: "鰻魚", ja: "ウナギ", ko: "장어", de: "Aal" }, qty: 1 }, { key: "hot-pepper", name: { en: "Hot Pepper", zh: "辣椒", zhTW: "辣椒", ja: "トウガラシ", ko: "매운 고추", de: "Peperoni" }, qty: 1 }], source: { en: "George (Mail - 7+)", zh: "乔治（邮件 - 7+）", zhTW: "喬治（郵件 - 7+）", ja: "ジョージ（手紙 - 7つ以上）", ko: "조지 (우편 - 7 이상)", de: "George (per Brief - 7+)" }, sourceCat: "friendship", energy: 115, health: 51, buffs: [{ type: "luck", amount: 1 }, { type: "speed", amount: 1 }], buffDuration: "7m", sellPrice: 175 },
  { key: "squid-ink-ravioli", icon: "Squid_Ink_Ravioli.png", name: { en: "Squid Ink Ravioli", zh: "墨汁意大利饺", zhTW: "墨汁意大利餃", ja: "イカスミのラビオリ", ko: "오징어 먹물 라비올리", de: "Tintenfisch-Tintenravioli" }, ingredients: [{ key: "squid-ink", name: { en: "Squid Ink", zh: "鱿鱼墨汁", zhTW: "魷魚墨汁", ja: "イカのインク", ko: "오징어 먹물", de: "Tintenfisch Tinte" }, qty: 1 }, { key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }], source: { en: "Combat Level 9", zh: "战斗 9级", zhTW: "戰鬥 9級", ja: "戦闘 レベル9", ko: "전투 레벨 9", de: "Kampf Stufe 9" }, sourceCat: "skill", energy: 125, health: 56, buffs: [{ type: "mining", amount: 1 }], buffDuration: "4m 39s (Mining) 2m 59s (Squid Ink Ravioli Buff)", sellPrice: 150 },
  { key: "stir-fry", icon: "Stir_Fry.png", name: { en: "Stir Fry", zh: "蔬菜什锦盖饭", zhTW: "蔬菜什錦蓋飯", ja: "野菜いため", ko: "야채 볶음", de: "Gemüsepfanne" }, ingredients: [{ key: "cave-carrot", name: { en: "Cave Carrot", zh: "山洞萝卜", zhTW: "山洞蘿蔔", ja: "洞窟ニンジン", ko: "동굴 당근", de: "Höhlenkarotte" }, qty: 1 }, { key: "common-mushroom", name: { en: "Common Mushroom", zh: "普通蘑菇", zhTW: "普通蘑菇", ja: "マッシュルーム", ko: "흔한 버섯", de: "Gewöhnlicher Pilz" }, qty: 1 }, { key: "kale", name: { en: "Kale", zh: "甘蓝菜", zhTW: "甘藍菜", ja: "ケール", ko: "케일", de: "Grünkohl" }, qty: 1 }, { key: "oil", name: { en: "Oil", zh: "油", zhTW: "油", ja: "オイル", ko: "기름", de: "Öl" }, qty: 1 }], source: { en: "The Queen of Sauce 7 Spring, Year 1", zh: "酱料女皇 奇数年春7日", zhTW: "醬料女皇 奇數年春7日", ja: "ソースの女王 １年目 春 7日", ko: "소스의 여왕 1년차 봄 7일", de: "Die Königin der Soßen 7. Frühling, Jahr 1" }, sourceCat: "tv", energy: 200, health: 90, buffs: [], buffDuration: null, sellPrice: 335 },
  { key: "strange-bun", icon: "Strange_Bun.png", name: { en: "Strange Bun", zh: "奇怪的小面包", zhTW: "奇怪的小麵包", ja: "おかしなパン", ko: "수상한 롤", de: "Komisches Brötchen" }, ingredients: [{ key: "wheat-flour", name: { en: "Wheat Flour", zh: "大麦粉", zhTW: "大麥粉", ja: "コムギ粉", ko: "밀가루", de: "Weizenmehl" }, qty: 1 }, { key: "periwinkle", name: { en: "Periwinkle", zh: "玉黍螺", zhTW: "玉黍螺", ja: "タマキビ", ko: "충알고둥", de: "Strandschnecke" }, qty: 1 }, { key: "void-mayonnaise", name: { en: "Void Mayonnaise", zh: "虚空蛋黄酱", zhTW: "虛空蛋黃醬", ja: "ヴォイドマヨネーズ", ko: "공허 마요네즈", de: "Schattenmayonnaise" }, qty: 1 }], source: { en: "Shane (Mail - 7+)", zh: "谢恩（邮件 - 7+）", zhTW: "謝恩（郵件 - 7+）", ja: "シェーン（手紙 - 7+）", ko: "셰인 (우편 - 7 이상)", de: "Shane (per Brief - 7+)" }, sourceCat: "friendship", energy: 100, health: 45, buffs: [], buffDuration: null, sellPrice: 225 },
  { key: "stuffing", icon: "Stuffing.png", name: { en: "Stuffing", zh: "塞料面包", zhTW: "塞料麵包", ja: "肉づめ", ko: "요리용 속", de: "Füllung" }, ingredients: [{ key: "bread", name: { en: "Bread", zh: "面包", zhTW: "麵包", ja: "パン", ko: "빵", de: "Brot" }, qty: 1 }, { key: "cranberries", name: { en: "Cranberries", zh: "蔓越莓", zhTW: "蔓越莓", ja: "クランベリー", ko: "크랜베리", de: "Preiselbeere" }, qty: 1 }, { key: "hazelnut", name: { en: "Hazelnut", zh: "榛子", zhTW: "榛子", ja: "ヘーゼルナッツ", ko: "헤이즐넛", de: "Haselnuss" }, qty: 1 }], source: { en: "Pam (Mail - 7+)", zh: "潘姆（邮件 - 7+）", zhTW: "潘姆（郵件 - 7+）", ja: "パム（手紙 - 7+）", ko: "팸 (우편 - 7 이상)", de: "Pam (per Brief - 7+)" }, sourceCat: "friendship", energy: 170, health: 76, buffs: [{ type: "defense", amount: 2 }], buffDuration: "5m 35s", sellPrice: 165 },
  { key: "super-meal", icon: "Super_Meal.png", name: { en: "Super Meal", zh: "巨无霸餐", zhTW: "巨無霸餐", ja: "パワフルいため", ko: "슈퍼 건강식", de: "Super-Mahlzeit" }, ingredients: [{ key: "bok-choy", name: { en: "Bok Choy", zh: "小白菜", zhTW: "小白菜", ja: "チンゲンサイ", ko: "청경채", de: "Senfkohl" }, qty: 1 }, { key: "cranberries", name: { en: "Cranberries", zh: "蔓越莓", zhTW: "蔓越莓", ja: "クランベリー", ko: "크랜베리", de: "Preiselbeere" }, qty: 1 }, { key: "artichoke", name: { en: "Artichoke", zh: "洋蓟", zhTW: "洋薊", ja: "アーティチョーク", ko: "아티초크", de: "Artischocke" }, qty: 1 }], source: { en: "Kent (Mail - 7+)", zh: "肯特（邮件 - 7+）", zhTW: "肯特（郵件 - 7+）", ja: "ケント（手紙 - 7+）", ko: "켄트 (우편 - 7 이상)", de: "Kent (per Brief - 7+)" }, sourceCat: "friendship", energy: 160, health: 72, buffs: [{ type: "maxEnergy", amount: 40 }, { type: "speed", amount: 1 }], buffDuration: "3m 30s", sellPrice: 220 },
  { key: "survival-burger", icon: "Survival_Burger.png", name: { en: "Survival Burger", zh: "救生汉堡", zhTW: "救生漢堡", ja: "サバイバルバーガー", ko: "생존형 버거", de: "Überlebensburger" }, ingredients: [{ key: "bread", name: { en: "Bread", zh: "面包", zhTW: "麵包", ja: "パン", ko: "빵", de: "Brot" }, qty: 1 }, { key: "cave-carrot", name: { en: "Cave Carrot", zh: "山洞萝卜", zhTW: "山洞蘿蔔", ja: "洞窟ニンジン", ko: "동굴 당근", de: "Höhlenkarotte" }, qty: 1 }, { key: "eggplant", name: { en: "Eggplant", zh: "茄子", zhTW: "茄子", ja: "ナス", ko: "가지", de: "Aubergine" }, qty: 1 }], source: { en: "Foraging Level 8", zh: "采集 8级", zhTW: "採集 8級", ja: "採取レベル8", ko: "채집 레벨 8", de: "Sammeln Stufe 8" }, sourceCat: "skill", energy: 125, health: 56, buffs: [{ type: "foraging", amount: 3 }], buffDuration: "5m 35s", sellPrice: 180 },
  { key: "tom-kha-soup", icon: "Tom_Kha_Soup.png", name: { en: "Tom Kha Soup", zh: "椰汁汤", zhTW: "椰汁湯", ja: "トムカーガイ", ko: "똠카 스프", de: "Tom Kha-Suppe" }, ingredients: [{ key: "coconut", name: { en: "Coconut", zh: "椰子", zhTW: "椰子", ja: "ココナッツ", ko: "코코넛", de: "Kokosnuss" }, qty: 1 }, { key: "shrimp", name: { en: "Shrimp", zh: "虾", zhTW: "蝦", ja: "エビ", ko: "새우", de: "Garnele" }, qty: 1 }, { key: "common-mushroom", name: { en: "Common Mushroom", zh: "普通蘑菇", zhTW: "普通蘑菇", ja: "マッシュルーム", ko: "흔한 버섯", de: "Gewöhnlicher Pilz" }, qty: 1 }], source: { en: "Sandy (Mail - 7+)", zh: "桑迪（邮件 - 7+）", zhTW: "桑迪（郵件 - 7+）", ja: "サンディ（手紙 - 7+）", ko: "샌디 (우편 - 7 이상)", de: "Sandy (per Brief - 7+)" }, sourceCat: "friendship", energy: 175, health: 78, buffs: [{ type: "farming", amount: 2 }, { type: "maxEnergy", amount: 30 }], buffDuration: "7m", sellPrice: 250 },
  { key: "tortilla", icon: "Tortilla.png", name: { en: "Tortilla", zh: "墨西哥薄饼", zhTW: "墨西哥薄餅", ja: "トルティーヤ", ko: "또띠아", de: "Tortilla" }, ingredients: [{ key: "corn", name: { en: "Corn", zh: "玉米", zhTW: "玉米", ja: "トウモロコシ", ko: "옥수수", de: "Mais" }, qty: 1 }], source: { en: "The Queen of Sauce 7 Fall, Year 1 Stardrop Saloon for 100g", zh: "酱料女皇 奇数年秋季7日 星之果实酒吧 价格100", zhTW: "醬料女皇 奇數年秋季7日 星之果實酒吧 價格100", ja: "ソースの女王 1年目の秋7日 スタードロップサルーンから100g", ko: "소스의 여왕 1년차 가을 7일 스타드롭 주점에서 100골드", de: "Die Königin der Soßen 7.Herbst, Jahr 1 Kneipe für 500 G" }, sourceCat: "tv", energy: 50, health: 22, buffs: [], buffDuration: null, sellPrice: 50 },
  { key: "triple-shot-espresso", icon: "Triple_Shot_Espresso.png", name: { en: "Triple Shot Espresso", zh: "三倍浓缩咖啡", zhTW: "三倍濃縮咖啡", ja: "トリプルショットエスプレッソ", ko: "트리플 샷 에스프레소", de: "Dreifacher Espresso" }, ingredients: [{ key: "coffee", name: { en: "Coffee", zh: "咖啡", zhTW: "咖啡", ja: "コーヒー", ko: "커피", de: "Kaffee" }, qty: 3 }], source: { en: "Stardrop Saloon for 5,000g", zh: "星之果实酒吧花费5,000", zhTW: "星之果實酒吧花費5,000", ja: "スタードロップサルーンから5,000gで購入", ko: "스타드롭 주점에서 5,000골드", de: "Kneipe zum Sternenfall für 5.000 G" }, sourceCat: "shop", energy: 8, health: 3, buffs: [{ type: "speed", amount: 1 }], buffDuration: "4m 12s", sellPrice: 450 },
  { key: "tropical-curry", icon: "Tropical_Curry.png", name: { en: "Tropical Curry", zh: "热带咖喱", zhTW: "熱帶咖喱", ja: "トロピカルカレー", ko: "열대 카레", de: "Tropisches Curry" }, ingredients: [{ key: "coconut", name: { en: "Coconut", zh: "椰子", zhTW: "椰子", ja: "ココナッツ", ko: "코코넛", de: "Kokosnuss" }, qty: 1 }, { key: "pineapple", name: { en: "Pineapple", zh: "菠萝", zhTW: "菠蘿", ja: "パイナップル", ko: "파인애플", de: "Ananas" }, qty: 1 }, { key: "hot-pepper", name: { en: "Hot Pepper", zh: "辣椒", zhTW: "辣椒", ja: "トウガラシ", ko: "매운 고추", de: "Peperoni" }, qty: 1 }], source: { en: "Ginger Island Resort for 2,000g", zh: "姜岛度假村", zhTW: "姜島度假村", ja: "ジンジャーアイランドリゾート", ko: "진저 섬 리조트", de: "Ingwerinsel Strandresort" }, sourceCat: "shop", energy: 150, health: 67, buffs: [{ type: "foraging", amount: 4 }], buffDuration: "5m 1s", sellPrice: 500 },
  { key: "trout-soup", icon: "Trout_Soup.png", name: { en: "Trout Soup", zh: "鳟鱼汤", zhTW: "鱒魚湯", ja: "マスのスープ", ko: "송어 스프", de: "Forellensuppe" }, ingredients: [{ key: "rainbow-trout", name: { en: "Rainbow Trout", zh: "虹鳟鱼", zhTW: "虹鱒魚", ja: "ニジマス", ko: "무지개송어", de: "Regenbogenforelle" }, qty: 1 }, { key: "green-algae", name: { en: "Green Algae", zh: "绿藻", zhTW: "綠藻", ja: "緑の藻", ko: "녹조류", de: "Grünalge" }, qty: 1 }], source: { en: "The Queen of Sauce 14 Fall, Year 1", zh: "酱料女皇 奇数年秋季14日", zhTW: "醬料女皇 奇數年秋季14日", ja: "ソースの女王 １年目 秋 14日", ko: "소스의 여왕 1년차 가을 14일", de: "Die Königin der Soßen 14. Herbst, Jahr 1" }, sourceCat: "tv", energy: 100, health: 45, buffs: [{ type: "fishing", amount: 1 }], buffDuration: "4m 39s", sellPrice: 100 },
  { key: "vegetable-medley", icon: "Vegetable_Medley.png", name: { en: "Vegetable Medley", zh: "蔬菜杂烩", zhTW: "蔬菜雜燴", ja: "野菜のシチュー", ko: "야채의 메들리", de: "Gemüseeintopf" }, ingredients: [{ key: "tomato", name: { en: "Tomato", zh: "西红柿", zhTW: "西紅柿", ja: "トマト", ko: "토마토", de: "Tomate" }, qty: 1 }, { key: "beet", name: { en: "Beet", zh: "甜菜", zhTW: "甜菜", ja: "ビーツ", ko: "사탕무", de: "Rübe" }, qty: 1 }], source: { en: "Caroline (Mail - 7+)", zh: "卡洛琳（邮件 - 7+）", zhTW: "卡洛琳（郵件 - 7+）", ja: "キャロライン（手紙 - 7+）", ko: "캐롤라인 (우편 - 7 이상)", de: "Caroline (per Brief - 7+)" }, sourceCat: "friendship", energy: 165, health: 74, buffs: [], buffDuration: null, sellPrice: 120 },
]

export function pickCook(l: CookLoc, locale: string): string {
  if (locale === 'zh') return l.zh
  if (locale === 'zh-TW') return l.zhTW
  if (locale === 'ja') return l.ja
  if (locale === 'ko') return l.ko
  if (locale === 'de') return l.de
  return l.en
}

export function allIngredients(locale: string): { key: string; name: string }[] {
  const map = new Map<string, string>()
  for (const r of COOK_RECIPES) {
    for (const ing of r.ingredients) {
      if (!map.has(ing.key)) map.set(ing.key, pickCook(ing.name, locale))
    }
  }
  return [...map.entries()]
    .map(([key, name]) => ({ key, name }))
    .sort((a, b) => a.name.localeCompare(b.name))
}

export interface RecipeFilter { ingredientKey: string; buff: BuffType | 'all'; sourceCat: SourceCat | 'all'; query: string; locale: string }

export function filterRecipes(f: RecipeFilter): CookRecipe[] {
  const q = f.query.trim().toLowerCase()
  return COOK_RECIPES.filter((r) => {
    if (f.ingredientKey && !r.ingredients.some((i) => i.key === f.ingredientKey)) return false
    if (f.buff !== 'all' && !r.buffs.some((b) => b.type === f.buff)) return false
    if (f.sourceCat !== 'all' && r.sourceCat !== f.sourceCat) return false
    if (q && !pickCook(r.name, f.locale).toLowerCase().includes(q)) return false
    return true
  })
}
