// AUTO-GENERATED from the official per-language Stardew Valley wiki (List of All Gifts).
// Loved gifts (+80 friendship). Do not edit by hand — regenerate from source.

export type GiftLoc = { en: string; zh: string; zhTW: string; ja: string; ko: string; de: string }
export type Season = 'spring' | 'summer' | 'fall' | 'winter'
export interface GiftVillager { en: string; name: GiftLoc; season: Season; day: number; loves: string[] }

export const GIFT_ITEMS: Record<string, GiftLoc> = {
  'Golden_Pumpkin': { en: 'Golden Pumpkin', zh: '黄金南瓜', zhTW: '黄金南瓜', ja: 'ゴールデンパンプキン', ko: '황금 호박', de: 'Goldener Kürbis' },
  'Magic_Rock_Candy': { en: 'Magic Rock Candy', zh: '魔法糖冰棍', zhTW: '魔法糖冰棍', ja: '魔法のロックキャンディ', ko: '마법 얼음사탕', de: 'Magischer Bonbon' },
  'Pearl': { en: 'Pearl', zh: '珍珠', zhTW: '珍珠', ja: 'しんじゅ', ko: '진주', de: 'Perle' },
  'Prismatic_Shard': { en: 'Prismatic Shard', zh: '五彩碎片', zhTW: '五彩碎片', ja: 'レインボージェム', ko: '무지갯빛 파편', de: 'Prismatische Scherbe' },
  'Rabbit\'s_Foot': { en: 'Rabbit\'s Foot', zh: '兔子的脚', zhTW: '兔子的脚', ja: 'ウサギの足', ko: '토끼발', de: 'Hasenpfote' },
  'Stardrop_Tea': { en: 'Stardrop Tea (+250)', zh: '星之果茶（+250）', zhTW: '星之果茶（+250）', ja: 'スタードロップティー（+250）', ko: '별방울차 (+250)', de: 'Sternenfall-Tee (+250)' },
  'Fiddlehead_Risotto': { en: 'Fiddlehead Risotto', zh: '意式蕨菜炖饭', zhTW: '意式蕨菜炖饭', ja: 'フィドルヘッドのリゾット', ko: '청나래고사리 리조또', de: 'Straußfarn-Risotto' },
  'Roasted_Hazelnuts': { en: 'Roasted Hazelnuts', zh: '烤榛子', zhTW: '烤榛子', ja: '焼きヘーゼルナッツ', ko: '구운 헤이즐넛', de: 'Geröstete Haselnüsse' },
  'Autumn\'s_Bounty': { en: 'Autumn\'s Bounty', zh: '秋日恩赐', zhTW: '秋日恩赐', ja: '秋のめぐみ', ko: '가을의 수확', de: 'Herbstfülle' },
  'Glazed_Yams': { en: 'Glazed Yams', zh: '琉璃山药', zhTW: '琉璃山药', ja: 'サツマイモのミツがけ', ko: '맛탕', de: 'Glasierte Süßkartoffeln' },
  'Green_Tea': { en: 'Green Tea', zh: '绿茶', zhTW: '绿茶', ja: '緑茶', ko: '녹차', de: 'Grüner Tee' },
  'Hot_Pepper': { en: 'Hot Pepper', zh: '辣椒', zhTW: '辣椒', ja: 'トウガラシ', ko: '매운 고추', de: 'Peperoni' },
  'Vegetable_Medley': { en: 'Vegetable Medley', zh: '蔬菜杂烩', zhTW: '蔬菜杂烩', ja: '野菜のシチュー', ko: '야채의 메들리', de: 'Gemüseeintopf' },
  'Cranberry_Candy': { en: 'Cranberry Candy', zh: '蔓越莓糖果', zhTW: '蔓越莓糖果', ja: 'クランベリーキャンディ', ko: '크랜베리 캔디', de: 'Preiselbeer-Süßigkeit' },
  'Green_Frog_Egg': { en: 'Frog Egg', zh: '青蛙蛋', zhTW: '青蛙蛋', ja: 'カエルのタマゴ', ko: '개구리알', de: 'Froschei' },
  'Ginger_Ale': { en: 'Ginger Ale', zh: '姜汁汽水', zhTW: '姜汁汽水', ja: 'ジンジャーエール', ko: '진저 에일', de: 'Ginger Ale' },
  'Grape': { en: 'Grape', zh: '葡萄', zhTW: '葡萄', ja: 'ブドウ', ko: '포도', de: 'Weintraube' },
  'Pink_Cake': { en: 'Pink Cake', zh: '粉红蛋糕', zhTW: '粉红蛋糕', ja: 'ピンクケーキ', ko: '핑크 케이크', de: 'Pinke Torte' },
  'Snail': { en: 'Snail', zh: '蜗牛', zhTW: '蜗牛', ja: 'カタツムリ', ko: '달팽이', de: 'Schnecke' },
  'Coconut': { en: 'Coconut', zh: '椰子', zhTW: '椰子', ja: 'ココナッツ', ko: '코코넛', de: 'Kokosnuss' },
  'Fruit_Salad': { en: 'Fruit Salad', zh: '水果沙拉', zhTW: '水果沙拉', ja: 'フルーツサラダ', ko: '과일 샐러드', de: 'Obstsalat' },
  'Sunflower': { en: 'Sunflower', zh: '向日葵', zhTW: '向日葵', ja: 'ヒマワリ', ko: '해바라기', de: 'Sonnenblume' },
  'Beer': { en: 'Beer', zh: '啤酒', zhTW: '啤酒', ja: 'ビール', ko: '맥주', de: 'Bier' },
  'Cactus_Fruit': { en: 'Cactus Fruit', zh: '仙人掌果子', zhTW: '仙人掌果子', ja: 'サボテンフルーツ', ko: '선인장 열매', de: 'Kaktus-Frucht' },
  'Mead': { en: 'Mead', zh: '蜜蜂酒', zhTW: '蜜蜂酒', ja: 'はちみつ酒', ko: '벌꿀 술', de: 'Met' },
  'Pale_Ale': { en: 'Pale Ale', zh: '淡啤酒', zhTW: '淡啤酒', ja: 'ペールエール', ko: '페일 에일', de: 'Helles Bier' },
  'Parsnip': { en: 'Parsnip', zh: '防风草', zhTW: '防风草', ja: 'パースニップ', ko: '파스닙', de: 'Pastinake' },
  'Parsnip_Soup': { en: 'Parsnip Soup', zh: '防风草汤', zhTW: '防风草汤', ja: 'パースニップのスープ', ko: '설탕당근 스프', de: 'Pastinakensuppe' },
  'Piña_Colada': { en: 'Piña Colada', zh: '椰林飘香', zhTW: '椰林飘香', ja: 'ピニャコラーダ', ko: '피나콜라다', de: 'Piña Colada' },
  'Pepper_Poppers': { en: 'Pepper Poppers', zh: '爆炒青椒', zhTW: '爆炒青椒', ja: '揚げトウガラシ', ko: '페퍼 파퍼', de: 'Paprika-Popper' },
  'Pizza': { en: 'Pizza', zh: '披萨', zhTW: '披萨', ja: 'ピザ', ko: '피자', de: 'Pizza' },
  'Fried_Calamari': { en: 'Fried Calamari', zh: '炸鱿鱼', zhTW: '炸鱿鱼', ja: 'イカフライ', ko: '오징어튀김', de: 'Gebratener Tintenfisch' },
  'Price_Catalogue': { en: 'Price Catalogue', zh: '价格目录', zhTW: '价格目录', ja: '値段表', ko: '가격 카탈로그', de: 'Preiskatalog' },
  'Amethyst': { en: 'Amethyst', zh: '紫水晶', zhTW: '紫水晶', ja: 'アメシスト', ko: '자수정', de: 'Amethyst' },
  'Aquamarine': { en: 'Aquamarine', zh: '海蓝宝石', zhTW: '海蓝宝石', ja: 'アクアマリン', ko: '아쿠아마린', de: 'Aquamarin' },
  'Cloth': { en: 'Cloth', zh: '布料', zhTW: '布料', ja: '布', ko: '옷감', de: 'Stoff' },
  'Emerald': { en: 'Emerald', zh: '绿宝石', zhTW: '绿宝石', ja: 'エメラルド', ko: '에메랄드', de: 'Smaragd' },
  'Jade': { en: 'Jade', zh: '翡翠', zhTW: '翡翠', ja: 'ヒスイ', ko: '옥', de: 'Jade' },
  'Parrot_Egg': { en: 'Parrot Egg', zh: '鹦鹉蛋', zhTW: '鹦鹉蛋', ja: 'オウムのタマゴ', ko: '앵무새 알', de: 'Papagei Ei' },
  'Ruby': { en: 'Ruby', zh: '红宝石', zhTW: '红宝石', ja: 'ルビー', ko: '루비', de: 'Rubin' },
  'Survival_Burger': { en: 'Survival Burger', zh: '救生汉堡', zhTW: '救生汉堡', ja: 'サバイバルバーガー', ko: '생존형 버거', de: 'Überlebensburger' },
  'Topaz': { en: 'Topaz', zh: '黄水晶', zhTW: '黄水晶', ja: 'トパーズ', ko: '토파즈', de: 'Topas' },
  'Wool': { en: 'Wool', zh: '动物毛', zhTW: '动物毛', ja: 'ウール', ko: '양털', de: 'Wolle' },
  'Ancient_Doll': { en: 'Ancient Doll', zh: '古代玩偶', zhTW: '古代玩偶', ja: '古代の人形', ko: '고대 인형', de: 'Alte Puppe' },
  'Fairy_Box': { en: 'Fairy Box', zh: '仙女盒', zhTW: '仙女盒', ja: 'フェアリーボックス', ko: '요정 상자', de: 'Feen-Kiste' },
  'Fairy_Rose': { en: 'Fairy Rose', zh: '玫瑰仙子', zhTW: '玫瑰仙子', ja: 'フェアリーローズ', ko: '요정장미', de: 'Feenrose' },
  'Plum_Pudding': { en: 'Plum Pudding', zh: '葡萄干布丁', zhTW: '葡萄干布丁', ja: 'プラムのプディング', ko: '자두 푸딩', de: 'Plumpudding' },
  'Strange_Doll_(green)': { en: 'Strange Doll (green)', zh: '诡异玩偶（绿）', zhTW: '诡异玩偶（绿）', ja: '奇妙な人形（緑）', ko: '이상한 인형 (녹색)', de: 'Merkwürdige Puppe (grün)' },
  'Strange_Doll_(yellow)': { en: 'Strange Doll (yellow)', zh: '诡异玩偶（黄）', zhTW: '诡异玩偶（黄）', ja: '奇妙な人形（黄）', ko: '이상한 인형 (노란색)', de: 'Merkwürdige Puppe (gelb)' },
  'Diamond': { en: 'Diamond', zh: '钻石', zhTW: '钻石', ja: 'ダイヤモンド', ko: '다이아몬드', de: 'Diamant' },
  'Escargot': { en: 'Escargot', zh: '法式田螺', zhTW: '法式田螺', ja: 'エスカルゴ', ko: '에스카르고', de: 'Schneckengericht' },
  'Fish_Taco': { en: 'Fish Taco', zh: '鱼肉卷', zhTW: '鱼肉卷', ja: 'フィッシュタコス', ko: '생선 타코', de: 'Fisch-Taco' },
  'Orange': { en: 'Orange', zh: '橙子', zhTW: '橙子', ja: 'オレンジ', ko: '오렌지', de: 'Orange' },
  'Tropical_Curry': { en: 'Tropical Curry', zh: '热带咖喱', zhTW: '热带咖喱', ja: 'トロピカルカレー', ko: '열대 카레', de: 'Tropisches Curry' },
  'Battery_Pack': { en: 'Battery Pack', zh: '电池组', zhTW: '电池组', ja: '電池', ko: '배터리 팩', de: 'Batterie' },
  'Cauliflower': { en: 'Cauliflower', zh: '花椰菜', zhTW: '花椰菜', ja: 'カリフラワー', ko: '콜리플라워', de: 'Blumenkohl' },
  'Cheese_Cauliflower': { en: 'Cheese Cauliflower', zh: '乳酪花椰菜', zhTW: '乳酪花椰菜', ja: 'カリフラワーのチーズ焼き', ko: '치즈 콜리플라워', de: 'Überbackener Blumenkohl' },
  'Dwarf_Gadget': { en: 'Dwarf Gadget', zh: '矮人小工具', zhTW: '矮人小工具', ja: 'ドワーフの装置', ko: '드워프 도구', de: 'Zwergengerät' },
  'Gold_Bar': { en: 'Gold Bar', zh: '金锭', zhTW: '金锭', ja: '金ののべ棒', ko: '금 주괴', de: 'Goldbarren' },
  'Iridium_Bar': { en: 'Iridium Bar', zh: '铱锭', zhTW: '铱锭', ja: 'イリジウムののべ棒', ko: '이리듐 주괴', de: 'Iridiumbarren' },
  'Miner\'s_Treat': { en: 'Miner\'s Treat', zh: '矿工特供', zhTW: '矿工特供', ja: 'マインキャンディ', ko: '광부의 간식', de: 'Bergarbeiter-Leckerbissen' },
  'Radioactive_Bar': { en: 'Radioactive Bar', zh: '放射性矿锭', zhTW: '放射性矿锭', ja: '放射性ののべ棒', ko: '방사능 주괴', de: 'Radioaktiver Barren' },
  'Rhubarb_Pie': { en: 'Rhubarb Pie', zh: '大黄派', zhTW: '大黄派', ja: 'ルバーブのパイ', ko: '대황 파이', de: 'Rhabarberkuchen' },
  'Strawberry': { en: 'Strawberry', zh: '草莓', zhTW: '草莓', ja: 'イチゴ', ko: '딸기', de: 'Erdbeere' },
  'Complete_Breakfast': { en: 'Complete Breakfast', zh: '完美早餐', zhTW: '完美早餐', ja: '朝食セット', ko: '완벽한 아침', de: 'Volles Frühstück' },
  'Jack_Be_Nimble,_Jack_Be_Thick': { en: 'Jack Be Nimble, Jack Be Thick', zh: '铜墙铁壁', zhTW: '铜墙铁壁', ja: 'ジャックはすばやくたくましく', ko: '날렵하렴 잭, 두꺼우렴 잭', de: 'Jack ist flink, Jack ist zäh' },
  'Salmon_Dinner': { en: 'Salmon Dinner', zh: '鲑鱼晚餐', zhTW: '鲑鱼晚餐', ja: 'サーモンディナー', ko: '연어 정찬', de: 'Lachs-Mahlzeit' },
  'Maple_Bar': { en: 'Maple Bar', zh: '枫糖棒', zhTW: '枫糖棒', ja: 'メープルバー', ko: '메이플 바', de: 'Ahornriegel' },
  'Tigerseye': { en: 'Tigerseye', zh: '虎眼石', zhTW: '虎眼石', ja: 'タイガーアイ', ko: '호안석', de: 'Tigerauge' },
  'Bean_Hotpot': { en: 'Bean Hotpot', zh: '豆类火锅', zhTW: '豆类火锅', ja: 'マメのシチュー', ko: '콩 스튜', de: 'Bohneneintopf' },
  'Ice_Cream': { en: 'Ice Cream', zh: '冰淇淋', zhTW: '冰淇淋', ja: 'アイスクリーム', ko: '아이스크림', de: 'Eis' },
  'Rice_Pudding': { en: 'Rice Pudding', zh: '大米布丁', zhTW: '大米布丁', ja: 'ライスプディング', ko: '라이스 푸딩', de: 'Milchreis' },
  'Lava_Eel': { en: 'Lava Eel', zh: '岩浆鳗鱼', zhTW: '岩浆鳗鱼', ja: '溶岩ウナギ', ko: '용암 장어', de: 'Lava-Aal' },
  'Lemon_Stone': { en: 'Lemon Stone', zh: '柠檬石', zhTW: '柠檬石', ja: 'レモンストーン', ko: '레몬 스톤', de: 'Zitronenstein' },
  'Omni_Geode': { en: 'Omni Geode', zh: '万象晶球', zhTW: '万象晶球', ja: 'オムニジオード', ko: '전 정동석', de: 'Omni-Geode' },
  'Catfish': { en: 'Catfish', zh: '鲶鱼', zhTW: '鲶鱼', ja: 'ナマズ', ko: '메기', de: 'Katzenfisch' },
  'Jewels_Of_The_Sea': { en: 'Jewels Of The Sea', zh: '海之宝石', zhTW: '海之宝石', ja: '海の宝石', ko: '바다의 보석', de: 'Juwelen des Meeres' },
  'Octopus': { en: 'Octopus', zh: '章鱼', zhTW: '章鱼', ja: 'タコ', ko: '문어', de: 'Oktopus' },
  'Pumpkin': { en: 'Pumpkin', zh: '南瓜', zhTW: '南瓜', ja: 'カボチャ', ko: '호박', de: 'Kürbis' },
  'Sea_Cucumber': { en: 'Sea Cucumber', zh: '海参', zhTW: '海参', ja: 'ナマコ', ko: '해삼', de: 'Seegurke' },
  'Sturgeon': { en: 'Sturgeon', zh: '鲟鱼', zhTW: '鲟鱼', ja: 'チョウザメ', ko: '철갑상어', de: 'Stör' },
  'The_Art_O\'_Crabbing': { en: 'The Art O\' Crabbing', zh: '捕蟹秘籍', zhTW: '捕蟹秘籍', ja: 'カニの学問', ko: '게잡이의 기술', de: 'Die Kunst des Krabbenspiels' },
  'Duck_Feather': { en: 'Duck Feather', zh: '鸭毛', zhTW: '鸭毛', ja: 'アヒルのハネ', ko: '오리깃털', de: 'Entenfeder' },
  'Mango': { en: 'Mango', zh: '芒果', zhTW: '芒果', ja: 'マンゴー', ko: '망고', de: 'Mango' },
  'Ostrich_Egg': { en: 'Ostrich Egg', zh: '鸵鸟蛋', zhTW: '鸵鸟蛋', ja: 'ダチョウのタマゴ', ko: '타조알', de: 'Straußenei' },
  'Poi': { en: 'Poi', zh: '夏威夷芋泥', zhTW: '夏威夷芋泥', ja: 'ポイ', ko: '포이', de: 'Poi' },
  'Melon': { en: 'Melon', zh: '甜瓜', zhTW: '甜瓜', ja: 'メロン', ko: '멜론', de: 'Melone' },
  'Poppy': { en: 'Poppy', zh: '虞美人花', zhTW: '虞美人花', ja: 'ポピー', ko: '양귀비', de: 'Mohn' },
  'Poppyseed_Muffin': { en: 'Poppyseed Muffin', zh: '虞美人籽松糕', zhTW: '虞美人籽松糕', ja: 'ポピーシードマフィン', ko: '양귀비씨 머핀', de: 'Mohnmuffin' },
  'Red_Plate': { en: 'Red Plate', zh: '红之盛宴', zhTW: '红之盛宴', ja: 'レッドサラダ', ko: '붉은 정식', de: 'Rote Platte' },
  'Roots_Platter': { en: 'Roots Platter', zh: '块茎拼盘', zhTW: '块茎拼盘', ja: '根菜盛り', ko: '뿌리채소 모음', de: 'Wurzelplatte' },
  'Sandfish': { en: 'Sandfish', zh: '沙鱼', zhTW: '沙鱼', ja: 'スナゴチ', ko: '도루묵', de: 'Sandfisch' },
  'Tom_Kha_Soup': { en: 'Tom Kha Soup', zh: '椰汁汤', zhTW: '椰汁汤', ja: 'トムカーガイ', ko: '똠카 스프', de: 'Tom Kha-Suppe' },
  'Crab_Cakes': { en: 'Crab Cakes', zh: '蟹黄糕', zhTW: '蟹黄糕', ja: 'クラブケーキ', ko: '게살 케이크', de: 'Krabbenkuchen' },
  'Lobster': { en: 'Lobster', zh: '龙虾', zhTW: '龙虾', ja: 'ロブスター', ko: '바닷가재', de: 'Hummer' },
  'Pomegranate': { en: 'Pomegranate', zh: '石榴', zhTW: '石榴', ja: 'ザクロ', ko: '석류', de: 'Granatapfel' },
  'Squid_Ink': { en: 'Squid Ink', zh: '鱿鱼墨汁', zhTW: '鱿鱼墨汁', ja: 'イカのインク', ko: '오징어 먹물', de: 'Tintenfisch Tinte' },
  'Chocolate_Cake': { en: 'Chocolate Cake', zh: '巧克力蛋糕', zhTW: '巧克力蛋糕', ja: 'チョコレートケーキ', ko: '초콜릿 케이크', de: 'Schokoladentorte' },
  'Crispy_Bass': { en: 'Crispy Bass', zh: '香酥鲈鱼', zhTW: '香酥鲈鱼', ja: 'バスのサクサク揚げ', ko: '우럭 튀김', de: 'Knuspriger Barsch' },
  'Eggplant_Parmesan': { en: 'Eggplant Parmesan', zh: '帕尔玛奶酪茄子', zhTW: '帕尔玛奶酪茄子', ja: 'ナスのチーズ焼き', ko: '가지 파마산', de: 'Auberginen-Parmesan' },
  'Fried_Eel': { en: 'Fried Eel', zh: '炒鳗鱼', zhTW: '炒鳗鱼', ja: 'ウナギフライ', ko: '장어튀김', de: 'Gebratener Aal' },
  'Pancakes': { en: 'Pancakes', zh: '薄煎饼', zhTW: '薄煎饼', ja: 'パンケーキ', ko: '팬케이크', de: 'Pfannkuchen' },
  'Banana_Pudding': { en: 'Banana Pudding', zh: '香蕉布丁', zhTW: '香蕉布丁', ja: 'バナナプリン', ko: '바나나 푸딩', de: 'Bananenpudding' },
  'Blackberry_Cobbler': { en: 'Blackberry Cobbler', zh: '黑莓脆皮饼', zhTW: '黑莓脆皮饼', ja: 'ブラックベリーパイ', ko: '블랙베리 코블러', de: 'Brombeer-Pastete' },
  'Monster_Compendium': { en: 'Monster Compendium', zh: '怪物图鉴', zhTW: '怪物图鉴', ja: 'モンスター図鑑', ko: '몬스터 개요서', de: 'Monster Kompendium' },
  'Pufferfish': { en: 'Pufferfish', zh: '河豚', zhTW: '河豚', ja: 'ハリセンボン', ko: '복어', de: 'Kugelfisch' },
  'Spicy_Eel': { en: 'Spicy Eel', zh: '香辣鳗鱼', zhTW: '香辣鳗鱼', ja: 'ピリ辛ウナギ', ko: '매콤한 장어', de: 'Würziger Aal' },
  'Crocus': { en: 'Crocus', zh: '番红花', zhTW: '番红花', ja: 'クロッカス', ko: '크로커스', de: 'Krokus' },
  'Daffodil': { en: 'Daffodil', zh: '黄水仙', zhTW: '黄水仙', ja: 'ラッパスイセン', ko: '수선화', de: 'Narzisse' },
  'Mango_Sticky_Rice': { en: 'Mango Sticky Rice', zh: '芒果糯米饭', zhTW: '芒果糯米饭', ja: 'マンゴーライス', ko: '카오 니야우 마무앙', de: 'Mango Klebreis' },
  'Sweet_Pea': { en: 'Sweet Pea', zh: '甜豌豆', zhTW: '甜豌豆', ja: 'スイートピー', ko: '스위트피', de: 'Edelwicke' },
  'Farmer\'s_Lunch': { en: 'Farmer\'s Lunch', zh: '农夫午餐', zhTW: '农夫午餐', ja: '牧場主のランチ', ko: '농부의 점심', de: 'Bauernmahlzeit' },
  'Pumpkin_Pie': { en: 'Pumpkin Pie', zh: '南瓜派', zhTW: '南瓜派', ja: 'パンプキンパイ', ko: '호박 파이', de: 'Kürbiskuchen' },
  'Goat_Cheese': { en: 'Goat Cheese', zh: '山羊奶酪', zhTW: '山羊奶酪', ja: 'ヤギのチーズ', ko: '염소 치즈', de: 'Ziegenkäse' },
  'Peach': { en: 'Peach', zh: '桃子', zhTW: '桃子', ja: 'モモ', ko: '복숭아', de: 'Pfirsich' },
  'Spaghetti': { en: 'Spaghetti', zh: '意大利面', zhTW: '意大利面', ja: 'スパゲッティ', ko: '스파게티', de: 'Spaghetti' },
  'Woody\'s_Secret': { en: 'Woody\'s Secret', zh: '伐木秘事', zhTW: '伐木秘事', ja: 'ウッディの秘密', ko: '우디의 비밀', de: 'Woodys Geheimnis' },
  'Fried_Mushroom': { en: 'Fried Mushroom', zh: '炒蘑菇', zhTW: '炒蘑菇', ja: 'キノコいため', ko: '버섯구이', de: 'Gebratene Pilze' },
  'Leek': { en: 'Leek', zh: '韭葱', zhTW: '韭葱', ja: 'ポロネギ', ko: '리크', de: 'Lauch' },
  'Monster_Musk': { en: 'Monster Musk', zh: '怪兽香水', zhTW: '怪兽香水', ja: 'モンスターの香り', ko: '몬스터 사향', de: 'Monster-Moschus' },
  'Void_Egg': { en: 'Void Egg', zh: '虚空蛋', zhTW: '虚空蛋', ja: 'ヴォイドエッグ', ko: '공허의 달걀', de: 'Schattenei' },
  'Void_Mayonnaise': { en: 'Void Mayonnaise', zh: '虚空蛋黄酱', zhTW: '虚空蛋黄酱', ja: 'ヴォイドマヨネーズ', ko: '공허 마요네즈', de: 'Schattenmayonnaise' },
  'Wild_Horseradish': { en: 'Wild Horseradish', zh: '野山葵', zhTW: '野山葵', ja: 'ノワサビ', ko: '야생 고추냉이', de: 'Wilder Meerrettich' },
  'Blueberry_Tart': { en: 'Blueberry Tart', zh: '蓝莓千层酥', zhTW: '蓝莓千层酥', ja: 'ブルーベリータルト', ko: '블루베리 타르트', de: 'Blaubeertörtchen' },
  'Dish_O\'_The_Sea': { en: 'Dish O\' The Sea', zh: '海之菜肴', zhTW: '海之菜肴', ja: 'おさかな定食', ko: '바다의 요리', de: 'Matrosenteller' },
  'The_Alleyway_Buffet': { en: 'The Alleyway Buffet', zh: '小巷自助餐', zhTW: '小巷自助餐', ja: '路地裏のビュッフェ', ko: '골목 뷔페', de: 'Das Gassenbuffet' },
  'Yam': { en: 'Yam', zh: '山药', zhTW: '山药', ja: 'サツマイモ', ko: '참마', de: 'Süßkartoffel' },
  'Summer_Spangle': { en: 'Summer Spangle', zh: '夏季亮片', zhTW: '夏季亮片', ja: 'サマースパングル', ko: '여름별꽃', de: 'Sommerschmuck' },
  'Frozen_Tear': { en: 'Frozen Tear', zh: '泪晶', zhTW: '泪晶', ja: 'イエティのなみだ', ko: '얼어붙은 눈물', de: 'Gefrorene Träne' },
  'Obsidian': { en: 'Obsidian', zh: '黑曜石', zhTW: '黑曜石', ja: '黒曜石', ko: '흑요석', de: 'Obsidian' },
  'Pumpkin_Soup': { en: 'Pumpkin Soup', zh: '南瓜汤', zhTW: '南瓜汤', ja: 'カボチャのスープ', ko: '호박죽', de: 'Kürbissuppe' },
  'Sashimi': { en: 'Sashimi', zh: '生鱼片', zhTW: '生鱼片', ja: '刺し身', ko: '회', de: 'Sashimi' },
  'Coffee': { en: 'Coffee', zh: '咖啡', zhTW: '咖啡', ja: 'コーヒー', ko: '커피', de: 'Kaffee' },
  'Pickles': { en: 'Pickles', zh: '腌菜', zhTW: '腌菜', ja: 'ピクルス', ko: '피클', de: 'Eingelegtes' },
  'Super_Meal': { en: 'Super Meal', zh: '巨无霸餐', zhTW: '巨无霸餐', ja: 'パワフルいため', ko: '슈퍼 건강식', de: 'Super-Mahlzeit' },
  'Truffle_Oil': { en: 'Truffle Oil', zh: '松露油', zhTW: '松露油', ja: 'トリュフオイル', ko: '송로버섯 오일', de: 'Trüffelöl' },
  'Wine': { en: 'Wine', zh: '果酒', zhTW: '果酒', ja: 'ワイン', ko: '와인', de: 'Wein' },
  'Book_of_Mysteries': { en: 'Book of Mysteries', zh: '谜之书', zhTW: '谜之书', ja: 'ミステリーの本', ko: '미스테리의 책', de: 'Buch der Mysterien' },
  'Purple_Mushroom': { en: 'Purple Mushroom', zh: '紫蘑菇', zhTW: '紫蘑菇', ja: 'むらさきキノコ', ko: '보라색 버섯', de: 'Violetter Pilz' },
  'Solar_Essence': { en: 'Solar Essence', zh: '太阳精华', zhTW: '太阳精华', ja: '光の結晶', ko: '태양 정수', de: 'Solar-Essenz' },
  'Super_Cucumber': { en: 'Super Cucumber', zh: '大海参', zhTW: '大海参', ja: 'スーパーナマコ', ko: '슈퍼해삼', de: 'Super-Seegurke' },
  'Void_Essence': { en: 'Void Essence', zh: '虚空精华', zhTW: '虚空精华', ja: '闇の結晶', ko: '공허 정수', de: 'Schattenessenz' },
  'Beet': { en: 'Beet', zh: '甜菜', zhTW: '甜菜', ja: 'ビーツ', ko: '사탕무', de: 'Rübe' },
  'Raisins': { en: 'Raisins', zh: '葡萄干', zhTW: '葡萄干', ja: '干しブドウ', ko: '건포도', de: 'Rosinen' },
  'Stuffing': { en: 'Stuffing', zh: '塞料面包', zhTW: '塞料面包', ja: '肉づめ', ko: '요리용 속', de: 'Füllung' },
  'Tulip': { en: 'Tulip', zh: '郁金香', zhTW: '郁金香', ja: 'チューリップ', ko: '튤립', de: 'Tulpe' },
  'Salad': { en: 'Salad', zh: '沙拉', zhTW: '沙拉', ja: 'サラダ', ko: '샐러드', de: 'Salat' },
  'Stir_Fry': { en: 'Stir Fry', zh: '蔬菜什锦盖饭', zhTW: '蔬菜什锦盖饭', ja: '野菜いため', ko: '야채 볶음', de: 'Gemüsepfanne' },
  'Truffle': { en: 'Truffle', zh: '松露', zhTW: '松露', ja: 'トリュフ', ko: '송로버섯', de: 'Trüffel' },
  'Artichoke_Dip': { en: 'Artichoke Dip', zh: '水煮洋蓟', zhTW: '水煮洋蓟', ja: 'アーティチョークディップ', ko: '아티초크 소스', de: 'Artischockendip' },
}

export const UNIVERSAL_LOVES: string[] = ['Golden_Pumpkin', 'Magic_Rock_Candy', 'Pearl', 'Prismatic_Shard', 'Rabbit\'s_Foot', 'Stardrop_Tea']

export const GIFT_VILLAGERS: GiftVillager[] = [
  { en: 'Kent', season: 'spring', day: 4, name: { zh: '肯特', zhTW: '肯特', en: 'Kent', ja: 'ケント', ko: '켄트', de: 'Kent' }, loves: ['Fiddlehead_Risotto', 'Roasted_Hazelnuts'] },
  { en: 'Lewis', season: 'spring', day: 7, name: { zh: '刘易斯', zhTW: '劉易斯', en: 'Lewis', ja: 'ルイス', ko: '루이스', de: 'Lewis' }, loves: ['Autumn\'s_Bounty', 'Glazed_Yams', 'Green_Tea', 'Hot_Pepper', 'Vegetable_Medley'] },
  { en: 'Vincent', season: 'spring', day: 10, name: { zh: '文森特', zhTW: '文森特', en: 'Vincent', ja: 'ヴィンセント', ko: '빈센트', de: 'Vincent' }, loves: ['Cranberry_Candy', 'Green_Frog_Egg', 'Ginger_Ale', 'Grape', 'Pink_Cake', 'Snail'] },
  { en: 'Haley', season: 'spring', day: 14, name: { zh: '海莉', zhTW: '海莉', en: 'Haley', ja: 'ヘイリー', ko: '헤일리', de: 'Haley' }, loves: ['Coconut', 'Fruit_Salad', 'Pink_Cake', 'Sunflower'] },
  { en: 'Pam', season: 'spring', day: 18, name: { zh: '潘姆', zhTW: '潘姆', en: 'Pam', ja: 'パム', ko: '팸', de: 'Pam' }, loves: ['Beer', 'Cactus_Fruit', 'Glazed_Yams', 'Mead', 'Pale_Ale', 'Parsnip', 'Parsnip_Soup', 'Piña_Colada'] },
  { en: 'Shane', season: 'spring', day: 20, name: { zh: '谢恩', zhTW: '謝恩', en: 'Shane', ja: 'シェーン', ko: '셰인', de: 'Shane' }, loves: ['Beer', 'Hot_Pepper', 'Pepper_Poppers', 'Pizza'] },
  { en: 'Pierre', season: 'spring', day: 26, name: { zh: '皮埃尔', zhTW: '皮埃爾', en: 'Pierre', ja: 'ピエール', ko: '피에르', de: 'Pierre' }, loves: ['Fried_Calamari', 'Price_Catalogue'] },
  { en: 'Emily', season: 'spring', day: 27, name: { zh: '艾米丽', zhTW: '艾米麗', en: 'Emily', ja: 'エミリー', ko: '에밀리', de: 'Emily' }, loves: ['Amethyst', 'Aquamarine', 'Cloth', 'Emerald', 'Jade', 'Parrot_Egg', 'Ruby', 'Survival_Burger', 'Topaz', 'Wool'] },
  { en: 'Jas', season: 'summer', day: 4, name: { zh: '贾斯', zhTW: '賈斯', en: 'Jas', ja: 'ジャス', ko: '재스', de: 'Jas' }, loves: ['Ancient_Doll', 'Fairy_Box', 'Fairy_Rose', 'Pink_Cake', 'Plum_Pudding', 'Strange_Doll_(green)', 'Strange_Doll_(yellow)'] },
  { en: 'Gus', season: 'summer', day: 8, name: { zh: '格斯', zhTW: '格斯', en: 'Gus', ja: 'ガス', ko: '거스', de: 'Gus' }, loves: ['Diamond', 'Escargot', 'Fish_Taco', 'Orange', 'Tropical_Curry'] },
  { en: 'Maru', season: 'summer', day: 10, name: { zh: '玛鲁', zhTW: '瑪魯', en: 'Maru', ja: 'マル', ko: '마루', de: 'Maru' }, loves: ['Battery_Pack', 'Cauliflower', 'Cheese_Cauliflower', 'Diamond', 'Dwarf_Gadget', 'Gold_Bar', 'Iridium_Bar', 'Miner\'s_Treat', 'Pepper_Poppers', 'Radioactive_Bar', 'Rhubarb_Pie', 'Strawberry'] },
  { en: 'Alex', season: 'summer', day: 13, name: { zh: '亚历克斯', zhTW: '亞歷克斯', en: 'Alex', ja: 'アレックス', ko: '알렉스', de: 'Alex' }, loves: ['Complete_Breakfast', 'Jack_Be_Nimble,_Jack_Be_Thick', 'Salmon_Dinner'] },
  { en: 'Sam', season: 'summer', day: 17, name: { zh: '山姆', zhTW: '山姆', en: 'Sam', ja: 'サム', ko: '샘', de: 'Sam' }, loves: ['Cactus_Fruit', 'Maple_Bar', 'Pizza', 'Tigerseye'] },
  { en: 'Demetrius', season: 'summer', day: 19, name: { zh: '德米特里厄斯', zhTW: '德米特里厄斯', en: 'Demetrius', ja: 'ディメトリウス', ko: '드미트리우스', de: 'Demetrius' }, loves: ['Bean_Hotpot', 'Ice_Cream', 'Rice_Pudding', 'Strawberry'] },
  { en: 'Dwarf', season: 'summer', day: 22, name: { zh: '矮人', zhTW: '矮人', en: 'Dwarf', ja: 'ドワーフ', ko: '드워프', de: 'Zwerg' }, loves: ['Amethyst', 'Aquamarine', 'Emerald', 'Jade', 'Lava_Eel', 'Lemon_Stone', 'Omni_Geode', 'Ruby', 'Topaz'] },
  { en: 'Willy', season: 'summer', day: 24, name: { zh: '威利', zhTW: '威利', en: 'Willy', ja: 'ウィリー', ko: '윌리', de: 'Willy' }, loves: ['Catfish', 'Diamond', 'Gold_Bar', 'Iridium_Bar', 'Jewels_Of_The_Sea', 'Mead', 'Octopus', 'Pumpkin', 'Sea_Cucumber', 'Sturgeon', 'The_Art_O\'_Crabbing'] },
  { en: 'Leo', season: 'summer', day: 26, name: { zh: '雷欧', zhTW: '雷歐', en: 'Leo', ja: 'レオ', ko: '레오', de: 'Leo' }, loves: ['Duck_Feather', 'Mango', 'Ostrich_Egg', 'Parrot_Egg', 'Poi'] },
  { en: 'Penny', season: 'fall', day: 2, name: { zh: '潘妮', zhTW: '潘妮', en: 'Penny', ja: 'ペニー', ko: '페니', de: 'Penny' }, loves: ['Diamond', 'Emerald', 'Melon', 'Poppy', 'Poppyseed_Muffin', 'Red_Plate', 'Roots_Platter', 'Sandfish', 'Tom_Kha_Soup'] },
  { en: 'Elliott', season: 'fall', day: 5, name: { zh: '艾利欧特', zhTW: '艾利歐特', en: 'Elliott', ja: 'エリオット', ko: '엘리엇', de: 'Elliott' }, loves: ['Crab_Cakes', 'Duck_Feather', 'Lobster', 'Pomegranate', 'Squid_Ink', 'Tom_Kha_Soup'] },
  { en: 'Jodi', season: 'fall', day: 11, name: { zh: '乔迪', zhTW: '喬迪', en: 'Jodi', ja: 'ジョディ', ko: '조디', de: 'Jodi' }, loves: ['Chocolate_Cake', 'Crispy_Bass', 'Diamond', 'Eggplant_Parmesan', 'Fried_Eel', 'Pancakes', 'Rhubarb_Pie', 'Vegetable_Medley'] },
  { en: 'Abigail', season: 'fall', day: 13, name: { zh: '阿比盖尔', zhTW: '阿比蓋爾', en: 'Abigail', ja: 'アビゲイル', ko: '애비게일', de: 'Abigail' }, loves: ['Amethyst', 'Banana_Pudding', 'Blackberry_Cobbler', 'Chocolate_Cake', 'Monster_Compendium', 'Pufferfish', 'Pumpkin', 'Spicy_Eel'] },
  { en: 'Sandy', season: 'fall', day: 15, name: { zh: '桑迪', zhTW: '桑迪', en: 'Sandy', ja: 'サンディ', ko: '샌디', de: 'Sandy' }, loves: ['Crocus', 'Daffodil', 'Mango_Sticky_Rice', 'Sweet_Pea'] },
  { en: 'Marnie', season: 'fall', day: 18, name: { zh: '玛妮', zhTW: '瑪妮', en: 'Marnie', ja: 'マーニー', ko: '마니', de: 'Marnie' }, loves: ['Diamond', 'Farmer\'s_Lunch', 'Pink_Cake', 'Pumpkin_Pie'] },
  { en: 'Robin', season: 'fall', day: 21, name: { zh: '罗宾', zhTW: '羅賓', en: 'Robin', ja: 'ロビン', ko: '로빈', de: 'Robin' }, loves: ['Goat_Cheese', 'Peach', 'Spaghetti', 'Woody\'s_Secret'] },
  { en: 'George', season: 'fall', day: 24, name: { zh: '乔治', zhTW: '喬治', en: 'George', ja: 'ジョージ', ko: '조지', de: 'George' }, loves: ['Fried_Mushroom', 'Leek'] },
  { en: 'Krobus', season: 'winter', day: 1, name: { zh: '科罗布斯', zhTW: '科羅布斯', en: 'Krobus', ja: 'クロバス', ko: '크로버스', de: 'Krobus' }, loves: ['Diamond', 'Iridium_Bar', 'Monster_Compendium', 'Monster_Musk', 'Pumpkin', 'Void_Egg', 'Void_Mayonnaise', 'Wild_Horseradish'] },
  { en: 'Linus', season: 'winter', day: 3, name: { zh: '莱纳斯', zhTW: '萊納斯', en: 'Linus', ja: 'ライナス', ko: '라이너스', de: 'Linus' }, loves: ['Blueberry_Tart', 'Cactus_Fruit', 'Coconut', 'Dish_O\'_The_Sea', 'The_Alleyway_Buffet', 'Yam'] },
  { en: 'Caroline', season: 'winter', day: 7, name: { zh: '卡洛琳', zhTW: '卡洛琳', en: 'Caroline', ja: 'キャロライン', ko: '캐롤라인', de: 'Caroline' }, loves: ['Fish_Taco', 'Green_Tea', 'Summer_Spangle', 'Tropical_Curry'] },
  { en: 'Sebastian', season: 'winter', day: 10, name: { zh: '塞巴斯蒂安', zhTW: '塞巴斯蒂安', en: 'Sebastian', ja: 'セバスチャン', ko: '세바스찬', de: 'Sebastian' }, loves: ['Green_Frog_Egg', 'Frozen_Tear', 'Obsidian', 'Pumpkin_Soup', 'Sashimi', 'Void_Egg'] },
  { en: 'Harvey', season: 'winter', day: 14, name: { zh: '哈维', zhTW: '哈維', en: 'Harvey', ja: 'ハーヴィー', ko: '하비', de: 'Harvey' }, loves: ['Coffee', 'Pickles', 'Super_Meal', 'Truffle_Oil', 'Wine'] },
  { en: 'Wizard', season: 'winter', day: 17, name: { zh: '法师', zhTW: '法師', en: 'Wizard', ja: '魔術師', ko: '마법사', de: 'Zauberer' }, loves: ['Book_of_Mysteries', 'Purple_Mushroom', 'Solar_Essence', 'Super_Cucumber', 'Void_Essence'] },
  { en: 'Evelyn', season: 'winter', day: 20, name: { zh: '艾芙琳', zhTW: '艾芙琳', en: 'Evelyn', ja: 'エブリン', ko: '에블린', de: 'Evelyn' }, loves: ['Beet', 'Chocolate_Cake', 'Diamond', 'Fairy_Rose', 'Raisins', 'Stuffing', 'Tulip'] },
  { en: 'Leah', season: 'winter', day: 23, name: { zh: '莉亚', zhTW: '莉亞', en: 'Leah', ja: 'リア', ko: '레아', de: 'Leah' }, loves: ['Goat_Cheese', 'Poppyseed_Muffin', 'Salad', 'Stir_Fry', 'Truffle', 'Vegetable_Medley', 'Wine'] },
  { en: 'Clint', season: 'winter', day: 26, name: { zh: '克林特', zhTW: '克林特', en: 'Clint', ja: 'クリント', ko: '클린트', de: 'Clint' }, loves: ['Amethyst', 'Aquamarine', 'Artichoke_Dip', 'Emerald', 'Fiddlehead_Risotto', 'Gold_Bar', 'Iridium_Bar', 'Jade', 'Omni_Geode', 'Ruby', 'Topaz'] },
]
